### ISSUE TITLE
[FEATURE] Allow role assumable by account outside of the organization

### ISSUE THREAD

**Issue by drewdresser** [aws-samples/aws-secure-environment-accelerator#1000]
**Required Basic Info**
- Accelerator Version:  1.5.1a

**Is your feature request related to a problem? Please describe.**
I would like to be able to create a role within the ASEA that is assumable by an account outside of the organization. Right now, the `getAccountId` method requires that the account is one which is defined in the config.json.

**Describe the solution you'd like**
I would like to be able to hard code an account ID in the role definition along with a star to specify that any role within that account can assume this role.

```json
{
  "role": "Demo-Role",
  "type": "ignore",
  "policies": ["AdministratorAccess"],
  "boundary-policy": "Default-Boundary-Policy",
  "trust-policy": "security-trust-policy.json",
  "source-account": "<AWS_ACCOUNT_ID>",
  "source-account-role": "*"
}
```

**Describe alternatives you've considered**
Or if I could just define this in the trust policy json file. My `security-trust-policy.json` file would have this in it:
```json
{
    "Version": "2012-10-17",
    "Statement": [
      {
        "Effect": "Allow",
        "Principal": {
          "AWS": "arn:aws:iam::<AWS_ACCOUNT_ID>:root"
        },
        "Action": "sts:AssumeRole"
      }
    ]
  }
```

**Additional context**
- It's possible I'm missing something with how roles are created and maybe this is possible.

**Comment by Brian969** [comment]
Your alternative option is supported today, see [FAQ1.6.15](https://aws-samples.github.io/aws-secure-environment-accelerator/faq/#how-do-i-create-a-role-for-use-by-azure-sentinel-using-the-new-s3-connector-method) or the [sample snippets](https://github.com/aws-samples/aws-secure-environment-accelerator/blob/main/reference-artifacts/SAMPLE_CONFIGS/sample_snippets.md) file for an example.

**Comment by Brian969** [comment]
- specify an account from within the org/ASEA config file (i.e. allow the role to be assumed from within the account that owns it)
- put your external account in the trust policy

**Comment by Brian969** [comment]
i.e. the role can be assumed from 2 spots 1) from within the ASEA account it is deployed (only from an all powerful role, like OrgAdminRole in the example), and 2) from your external account which is not part of the ASEA.

**Comment by drewdresser** [comment]
Awesome, thank you. This works:
```json
{
  "role": "Demo-Role",
  "type": "ignore",
  "policies": ["AdministratorAccess"],
  "boundary-policy": "Default-Boundary-Policy",
  "trust-policy": "security-trust-policy.json",
  "source-account": "management",
  "source-account-role": "AWSControlTowerExecution"
}
```
And the `security-trust-policy.json` is:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
        "Effect": "Allow",
        "Principal": {
            "AWS": "arn:aws:iam::845882744474:root"
        },
        "Action": "sts:AssumeRole"
        }
    ]
}
```
