### ISSUE TITLE
[FEATURE] Auto-create workload account Private Hosted Zones attached to shared VPC's

### ISSUE THREAD

**Issue by jblaplace** [aws-samples/aws-secure-environment-accelerator#1001]
**Required Basic Info**
To properly assess the enhancement request, we require information on the version of the Accelerator you based this request upon:
- Accelerator Version:  v1.5.1

**Is your feature request related to a problem? Please describe.**
Creating a Private Hosted Zone attached to a shared VPC in a workload account is possible but requires mutiple manual manipulation and involves high privilege roles.

**Describe the solution you'd like**
We would like to be able to create a PHZ attached to a shared VPC and have the PHZ owned/manageable by the workload account.
The PHZ creation would be made through the State Machine using the ASEA config file

**Describe alternatives you've considered**

**Additional context**

**Comment by archikierstead** [comment]
ASEA not working on new features see README.

**Comment by archikierstead** [comment]
ASEA not working on new features see README.
