### ISSUE TITLE
[BUG][SM] Default Lambda limit on new account causes the bootstrap environment process to fail.

### ISSUE THREAD

**Issue by mark-williams-mobilise** [aws-samples/aws-secure-environment-accelerator#1002]
Bug reports which fail to provide the required information will be closed without action.

**Required Basic Info**
- Accelerator Version:  v1.5.1-a
- Install Type: Clean
- Upgrade from version: N/A
- Which State did the Main State Machine Fail in: Bootstrap Enviroment

**Describe the bug**
A recent change to the default lambda limits on new accounts to a concurrent limit of 10 rather than the default 1000, has caused the bootstrap to fail as it tries to deploy more than 10 at the same time.

**Failure Info**
- What error messages have you identified, if any: 
- "error": "Lambda.TooManyRequestsException",
  "cause": "Rate Exceeded. (Service: Lambda, Status Code: 429, Request ID: a46ca17f-6589-42b6-87e4-2da239bb11e5)"
- What symptoms have you identified, if any:
- failed install

**Required files**
- issue is not related to a configuration 

**Steps To Reproduce**
1. Start deployment in a new AWS account
2. See error

**Expected behavior**
Roll out successfully without Rate Exceeded errors

**Screenshots**

**Additional context**
We have managed to get around the issue by requesting a service limit increase and waiting for the limits to be amended before successfully rerunning the deployment.  However a limit of 10 concurrent lambda calls during the deployment would have saved us a couple of days.
Ec2 were launched several times and let to run up to t3.large to ensure account was not limited but this did not help.

**Comment by kbroughton** [comment]
I deployed the ultralight + 3 workload accounts, which is still under the number of accounts if you have a lite- or full- setup. Still, I hit the limits. And AWS support declined my request to increase them.

```
Our Lambda service team has completed their review of your quota adjustment, and they have determined it cannot be approved at this time.

Because your account is still so new it lacks the consistent usage and billing history required to be eligible for quota adjustments.

You are encouraged to work within your existing quotas to build up your account history.
```

Are these super-strict lambda limits a new thing? If so, it seems like all new deployments of ASEA are doomed to fail.

**Comment by Brian969** [comment]
Are these super-strict lambda limits a new thing?  

- Unfortunately, Yes.  We are looking into the best way to work around this challenge. Until that time, if you reach out to your assigned account SA (assuming you have one), they can likely get these limits increased for you.
