### ISSUE TITLE
[FEATURE] Provide instructions to destroy org

### ISSUE THREAD

**Issue by kbroughton** [aws-samples/aws-secure-environment-accelerator#1004]
**Required Basic Info**

- Accelerator Version:  any

**Is your feature request related to a problem? Please describe.**
If the state machine gets into a bad state and you need to start over, there are a dozen accounts to destroy. But even logging
in as root, you don't have permissions to delete the account. What are the steps required to make this possible?

**Describe the solution you'd like**
Clear documentation on how to remove SCPs and delete accounts.

**Describe alternatives you've considered**
NA

**Additional context**
We tried for 3 weeks to get the accelerator working, but finally, had to give up. The root user for the root account cannot remove the SCP in place from the State Machine. Sub-account root users cannot delete the accounts.

**Comment by Brian969** [comment]
An example uninstall script and instructions, meant for NON-PRODUCTION environments can be found [here](https://github.com/aws-samples/aws-secure-environment-accelerator/tree/main/reference-artifacts/Custom-Scripts/SEA-uninstall).
