### ISSUE TITLE
[BUG][Functional] Log-archive resource policy sized exceeded in large environments

### ISSUE THREAD

**Issue by Brian969** [aws-samples/aws-secure-environment-accelerator#1030]
**Required Basic Info**
- Accelerator Version:  v1.5.3

**Describe the bug**
- In large ASEA deployments the CWL resource policy exceeds the maximum 5120 policy size limit
-Need to move to organization based policy

**Failure Info**
- notes available internally

**Comment by archikierstead** [comment]
Did not implement
