### ISSUE TITLE
[BUG][Functional] ASEA Config doesn't disables sending of SSM logs to CloudWatch

### ISSUE THREAD

**Issue by kaushikarvind** [aws-samples/aws-secure-environment-accelerator#1061]
Bug reports which fail to provide the required information will be closed without action.

**Required Basic Info**
- Accelerator Version:  (eg. v1.5.1-a)
- Install Type: (Upgrade)
- Upgrade from version: (v1.3.9)

**Describe the bug**
Running the Step Functions with the Global-option of 'ssm-to-cwl: false' does'nt disable the sending of SSM logs to CloudWatch

**Failure Info**
- What error messages have you identified, if any:
1- The Step Functions executes with no error, but the configuration in the Workload Account's Systems Manager --> Session Manager --> Configure Preferences does'nt disables the feature of CloudWatch Logging
2- Even executing the Step Function with input to over-ride the global-options does'nt disable the config setting
{
  "scope": "FULL",
  "mode": "APPLY",
  "configOverrides": {
    "ov-global-options": true
  }
}
- What symptoms have you identified, if any:
![image](https://user-images.githubusercontent.com/56485562/192531944-00457444-0d66-4700-b248-64e731faf396.png)

**Required files**
- copy of config.json file attached: 
[config.zip](https://github.com/aws-samples/aws-secure-environment-accelerator/files/9657137/config.zip)

**Steps To Reproduce**
1. Update the config.yaml
2. change the global-option of 'ssm-to-cwl: true' to 'ssm-to-cwl: false'
3. save & update the config.yaml
4. re-run the ASEA Step Function
5. Log in to any Workload Account
6. Choose the AWS Systems Manager service
7. Choose Session Manager under the Node Management on the left pane
8. Click on 'Configure Preferences' to open up setting page
9. Scroll down to CloudWatch Logging section
10. Enable checkbox is still 'checked' for CloudWatch logging

**Expected behavior**
If all was to work perfectly, the checkbox should be disabled for CloudWatch logging, disabling the shipping of SSM logs over to CloudWatch

**Screenshots**
screenshot attached above in the Failure Info section

**Additional context**
The functional requirement is to stop sending SSM logs to CloudWatch. It's Ok if they are getting collected in a S3 bucket

**Comment by archikierstead** [comment]
Did not implement
