### ISSUE TITLE
[BUG][Functional] unable to delete an msk connector.

### ISSUE THREAD

**Issue by abdelsgithub** [aws-samples/aws-secure-environment-accelerator#1084]
Unable to delete an msk connector attached to a log group.

Error message :
There is an issue with the connector
Code: InvalidInput.WorkerLogsError
Message: Could not enable/disable worker logs. For more information, see the Amazon MSK Connect Developer Guide. Message: User:xxxxxx assumed-role/xxxxx 
is not authorized to perform: logs:DeleteLogDelivery with an explicit deny in a service control policy

We have a same issue with a stage in an API gateway ressource

**Comment by archikierstead** [comment]
SCP configuration issue, not a bug
