### ISSUE TITLE
[BUG][OTHER] Reference SCP files are larger than the 5120 byte limit.

### ISSUE THREAD

**Issue by ghost** [aws-samples/aws-secure-environment-accelerator#1092]
**Required Basic Info**
- Accelerator Version:  v1.5.5
- Install Type: Upgrade
- Upgrade from version: N/A
- Which State did the Main State Machine Fail in: N/A

**Describe the bug**
The SCP files provided in this repo in thee `reference-artifacts` folder are larger than the allowed limit of 5120 bytes: https://docs.aws.amazon.com/organizations/latest/userguide/org_troubleshoot_policies.html#scptoolong. We have tried "minifying" the files by removing all newlines and condensing all spaces, etc., however even after that the `Part1` and `Part0-Core` policies are larger than the maximum allowed size.
This issue can be confirmed by going into SCPs in AWS Console and attempting to update an SCP by pasting in the contents of one of the two aforementioned reference SCPs.

**Failure Info**
- What error messages have you identified, if any: 
  - "Policy document exceeds maximum size"
- What symptoms have you identified, if any: 
  - SCPs fail to be applied via the state machine.
    ```{
    "errorType": "ConstraintViolationException",
    "errorMessage": "You have exceeded the maximum policy size.",
    "trace": [
      "ConstraintViolationException: You have exceeded the maximum policy size.",
      "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)",
      "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
      "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
      "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)",
      "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
      "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
      "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
      "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
      "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)",
      "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
    ]
    }

  - Attempting to manually update SCPs via AWS Console results in the same document maximum size error. 


**Steps To Reproduce**
1. Update SCPs in the environment as per ASEA instructions. Use the reference SCPs as provided in this repository without changing anything.
2. Run the main state machine.
3. Wait for it to fail when verifying SCPs.
    1. Upon examining the state machine's logs, the error that comes back is "You have exceeded the maximum policy size."

**Expected behavior**
The SCPs provided to us should not violate AWS' maximum size limits.

**Comment by Brian969** [comment]
- Not sure what you are attempting, but the reference SCP's are NOT larger than 5120 bytes when using any of the sample config files;
- The ASEA DOES automatically apply minification;
- if you look at the config file, it uses "reference variables" (i.e. ${variable}) which are replaced before application.  If you paste the SCPs verbatim, yes they exceed 5120 bytes - but they are also invalid (i.e. ${ACCELERATOR_PREFIX_ND} resolves to ASEA, shrinking the file, so you'd need to manual replace all the variables).
- as some variables are defined in the config file (ADDL_REGIONS_A), make sure a) they are defined, b) they do not resolve to something too large.
