### ISSUE TITLE
[FEATURE] Enable GuardDuty on Organizations Management Root

### ISSUE THREAD

**Issue by para0056** [aws-samples/aws-secure-environment-accelerator#1093]
**Required Basic Info**
To properly assess the enhancement request, we require information on the version of the Accelerator you based this request upon:
- Accelerator Version: v1.5.3

**Is your feature request related to a problem? Please describe.**
ASEA currently performs the following automatically on workload accounts:
- Enable GuardDuty
- Add account as member account in the security-audit GuardDuty console 

However, these automations do not apply to the Organizations Management Root account.
GuardDuty needs to be manually enabled, and the account needs to be manually added as a member in the security-audit GuardDuty console.

**Describe the solution you'd like**
Automate the enabling of GuardDuty in the Organizations Management Root account once the Security-audit account has been properly setup.

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by archikierstead** [comment]
Did not implement
