### ISSUE TITLE
[BUG][Functional] Inspector2 auto enrollment causes state machine failure on Phase 2

### ISSUE THREAD

**Issue by JustDYates** [aws-samples/aws-secure-environment-accelerator#1095]
Bug reports which fail to provide the required information will be closed without action.

**Required Basic Info**
- Accelerator Version: 1.5.5
- Install Type: Clean
- Upgrade from version: N/A

**Describe the bug**
Inspector auto-enrollment creates an SSM-GatherInventory document that conflicts with SEA, causing the state machine to fail on Phase-2 when the following is set in the SEA config: "ssm-inventory-collection": true

**Failure Info**
- What error messages have you identified, if any: 

Resource handler returned message: "Error occurred during operation 'CreateAssociation'." (RequestToken: token, HandlerErrorCode: GeneralServiceException)

486 | new GatherInventory (/app/src/lib/cdk-constructs/src/ssm/ssm-inventory.ts:49:9)
487 | \_ Object.inventoryCollection (/app/src/deployments/cdk/src/deployments/ssm/inventory-collection.ts:54:13)
488 | \_ deploy (/app/src/deployments/cdk/src/apps/phase-2.ts:465:25)
489 | \_ processTicksAndRejections (internal/process/task_queues.js:95:5)
490 | \_ Object.deploy (/app/src/deployments/cdk/src/app.ts:86:5)
491 | \_ main (/app/src/deployments/cdk/cdk.ts:109:18)
492 | {"stackName":"Workload-Phase2","stackEnvironment":{"account":"account","region":"region","name":"aws://account/region"},"assumeRoleArn":"arn:aws:iam::account:role/ASEA-PipelineRole","message":"Failed to deploy: Error: The stack named ASEA-Workload-Phase2 failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: \"Error occurred during operation 'CreateAssociation'.\" (RequestToken: token, HandlerErrorCode: GeneralServiceException)","messageType":"ERROR"}

- What symptoms have you identified, if any:
State machine failure on Phase-2 until the Inspector GatherInventory association is deleted

**Steps To Reproduce**
1. Enable inspector2 auto enrollment
2. Vend an account

**Screenshots**

![Inspector](https://user-images.githubusercontent.com/86789242/203528859-fae02dc3-448d-4542-8f82-bd817f5ab07b.PNG)

**Comment by archikierstead** [comment]
Will not fix
