### ISSUE TITLE
[BUG] [SM] Phase 1 fails to deploy IAM policy with a "Not Action"

### ISSUE THREAD

**Issue by joshvmaws** [aws-samples/aws-secure-environment-accelerator#1098]
**Required Basic Info**
- Accelerator Version:  1.15
- Install Type: Clean
- Upgrade from version: N/A
- Which State did the Main State Machine Fail in: "Deploy Phase 1"

**Describe the bug**
Fails to deploy IAM policies with a "Not Action"

**Failure Info**
- When deploying an iam policy (that has a NotAction) to an account via asea config (link to config object below), it fails
(https://aws-samples.github.io/aws-secure-environment-accelerator/schema/en/interfaces/IAMPolicyConfig.html)
- The code in src/deployments/cdk/src/common/iam-assets.ts does not include NotAction in **CfnIamPolicyOutput**  (around line 60)
    
![image](https://user-images.githubusercontent.com/96628998/207773988-65f31cc6-2cc0-4809-8090-c8c3e46cd318.png)

- This fails Phase 1 when the stack is being validated with the following errors in code build
   
![image](https://user-images.githubusercontent.com/96628998/207774094-bb14817b-571f-4057-9f65-fde3646258a9.png)

 
**Required files**
- An example policy that I tried to deploy
[permission-policy.txt](https://github.com/aws-samples/aws-secure-environment-accelerator/files/10233769/permission-policy.txt)

**Steps To Reproduce**
1. Deploy a simple policy with a NotAction

**Expected behavior**
Should be able to deploy any valid policy

**Screenshots**
![image](https://user-images.githubusercontent.com/96628998/207773796-ca366afc-b1f4-4243-9db2-6344f7150af9.png)

**Comment by archikierstead** [comment]
Did not implement
