### ISSUE TITLE
[BUG][Functional] Cannot enforce AWS Organizations Tag Policies

### ISSUE THREAD

**Issue by jfollenfant** [aws-samples/aws-secure-environment-accelerator#1103]
Bug reports which fail to provide the required information will be closed without action.

**Required Basic Info**
- Accelerator Version:  v1.5.5
- Install Type: clean

**Describe the bug**
Policies defined within AWS Organizations Tag Policies cannot be enforced on target OUs, they are automatically removed. This makes enforcement of Tag policies impossible.

**Failure Info**
The CloudWatch Events Rule PolicyChanges_rule (defined in us-east-1) kicks upon detection of a CloudTrail Event "AttachPolicy" and will trigger a "DetachPolicy" action.

**Steps To Reproduce**
1. Go to AWS Organizations console in Policies section, enable Tag Policies
2. Create a Tag Policy
3. Attach the policy on the desired OU
4. After a while the policy is removed

**Expected behavior**
Tag policies should not be automatically detached of their Target OUs

**Comment by archikierstead** [comment]
Fixed in 1.5.7
