### ISSUE TITLE
[BUG][Functional] TGW configurations missing and resources not created in team account when new vpc defined in Dev OU

### ISSUE THREAD

**Issue by evollebekk** [aws-samples/aws-secure-environment-accelerator#1110]
**Required Basic Info**
- Accelerator Version:   v1.5.5
- Install Type: Upgrade
- Upgrade from version: v1.5.4-a

**Describe the bug**
In support of a AWS Outposts deployment I am attempting to:
 - create a new VPC in an account I've created for the Outpost (Outpost Account)
 - share the new VPC (Outpost_Dev_vpc) with the Dev OU
 - provide connectivity to other ASEA VPCs and resources through the TGW

The new Outpost_Dev_vpc has been defined in the Dev Ou section of the ASEA config.json and the Outpost Account was set as the targeted account.  Subnets were defined to be created in region (Outpost_TGW) and on the Outpost (Outpost_Web, Outpost_App, Outpost_Data). A TGW attachment was also defined to associate the new Outpost_Dev_vpc with the segregated route table and create propagations to the core and shared TGW route tables.  After running the ASEA step function several of the expected resources weren't created within the Dev OU shared Dev-Team-1 Team/Workload account and TGW configurations were missing in the Shared Network account. 

![example_outpost_network](https://user-images.githubusercontent.com/32405166/219132122-a1e7a6ba-4e9a-47ae-846d-77666bdbd7cf.PNG)

**Failure Info**
The following is a breakdown of expected resources that failed to be created.

In the Shared Network account
- A new TGW attachment was created for the Outpost_Dev_vpc but the attachment name was missing and the attachment wasn't associated with the expected Main_tgw_segregated_rt  TGW route table
- The Main_tgw_shared_rt is missing the expected propagation for the Outpost_Dev_vpc
- The Main_tgw_core_rt is missing the expected propagation for the Outpost_Dev_vpc

In the Dev OU shared Dev-Team-1 Team/Workload account
- Security groups were created in the Outposts account which contains the Outpost_Dev_vpc but were not created in the Dev OU member accounts.
- The Outpost_Dev_vpc was shared with the Dev OU member team/workload accounts but the VPC name tag is missing
- The Outpost_Dev_vpc subnets were shared with the Dev OU member team/workload accounts but the Subnet name tags are missing
- The Outpost_Dev_vpc route tables were shared with the Dev OU member team/workload accounts but the route table name tags are missing.  Note that this issue also occurs with the existing Dev_vpc.
- The Outpost_Dev_vpc NACLs were shared with the Dev OU member team/workload accounts but the NACL name tags are missing.  Note that this issue also occurs with the existing Dev_vpc.

**Required files**
- Attached is the Dev OU section of the config.json file

[config-example-outpost-network.json.txt](https://github.com/aws-samples/aws-secure-environment-accelerator/files/10746701/config-example-outpost-network.json.txt)

**Expected behavior**
- The new TGW attachment is given a name and is associated with the route table specified in the tgw-rt-associate property
- Propagations for the new vpc are created in the route tables specified in the tgw-rt-propagate property
- VPCs, subnets, route tables and NACLs in Dev OU member accounts are given a name tag
- Security groups are created in Dev OU member accounts that match the SGs in the account sharing the VPC

**Comment by archikierstead** [comment]
Fix was to shorten the length of the account names (concatenated).
