### ISSUE TITLE
[FEATURE] Modification of the "ASEA-Guardrails-Sensitive" SCP to allow IAM Identity Center Delegated Administrator functionality

### ISSUE THREAD

**Issue by joeldesaulniers** [aws-samples/aws-secure-environment-accelerator#1147]
**Required Basic Info**
- Accelerator Version:  v1.5.6-a

**Is your feature request related to a problem? Please describe.**
An ASEA customer that sets up IAM Identity Center, Delegated Administrator to be their Security account cannot properly administer the IAM Identity Center multi-account permissions. When they login to their Security account and click on IAM Identity Center -> Multi-Account Permissions -> AWS Accounts (or Permission Sets), an error message indicating "unsuccessful HTTP response" is returned. This is due to the "ASEA-Guardrails-Sensitive" SCP applied to the account's OU.

**Describe the solution you'd like**
Modification of the "ASEA-Guardrails-Sensitive" SCP available in https://github.com/aws-samples/aws-secure-environment-accelerator/blob/main/reference-artifacts/SCPs/ASEA-Guardrails-Sensitive.json to add the statement "sso:DescribeRegisteredRegions" under "GBP1" -> "NotAction" section.

**Describe alternatives you've considered**
An alternative is to ask the customer to assume the ASEA-Pipeline role, but that is NOT a recommended approach for security reasons.

**Additional context**
Screenshot of the issue below. Also including a screenshot of the statement to be added to the SCP.
<img width="997" alt="Screenshot 2023-05-03 at 11 21 45 AM" src="https://user-images.githubusercontent.com/60636149/235962065-b083adfa-f870-4317-9cce-db89efd548bd.png">

<img width="366" alt="Screenshot 2023-05-03 at 11 21 55 AM" src="https://user-images.githubusercontent.com/60636149/235962123-3e2100d7-5609-4d58-9137-c6a03738211f.png">

**Comment by archikierstead** [comment]
Raised PR, will merge for next release.
