### ISSUE TITLE
[FEATURE] Remove retired AWS Security Hub controls

### ISSUE THREAD

**Issue by ColinL2021** [aws-samples/aws-secure-environment-accelerator#1192]
**Required Basic Info**
To properly assess the enhancement request, we require information on the version of the Accelerator you based this request upon:
- Accelerator Version:  v1.5.8-a

**Is your feature request related to a problem? Please describe.**
There are AWS Security Hub controls that have retired.
Refer to : https://docs.aws.amazon.com/securityhub/latest/userguide/doc-history.html

Retiring the **Lambda.4** control: 
Security Hub is retiring the control [Lambda.4] Lambda functions should have a dead-letter queue configured.  When                     a control is retired, it no longer displays on the  console, and Security Hub does not perform checks against it.

Retiring the **PCI.EC2.3** control:
Security Hub is retiring the control [PCI.EC2.3] Unused EC2 security groups should be removed. When a control is                     retired, it no longer displays on the console, and Security Hub does not perform checks against it. 

**Describe the solution you'd like**
Remove the controls **Lambda.4** and **PCI.EC2.3** from all sample configs in the "security-hub-frameworks" section under "controls-to-disable".

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by archikierstead** [comment]
merged
