### ISSUE TITLE
[FEATURE] Allow usage of Amazon AppFlow

### ISSUE THREAD

**Issue by ColinL2021** [aws-samples/aws-secure-environment-accelerator#1198]
**Required Basic Info**
To properly assess the enhancement request, we require information on the version of the Accelerator you based this request upon:
- Accelerator Version:  v1.5.8

**Is your feature request related to a problem? Please describe.**

The Amazon AppFlow service is now on the list of CCCS assessed services. Currently the Sandbox, UnClass, and Sensitive SCP's block the usage of Amazon AppFlow.

**Describe the solution you'd like**

Remove Amazon AppFlow from the Sandbox, UnClass, and Sensitive SCP's to allow usage of the service.

**Describe alternatives you've considered**

None

**Additional context**

List of CCCS assessed services can be found here: https://aws.amazon.com/compliance/services-in-scope/CCCS/

**Comment by archikierstead** [comment]
Closing, will not implement.  Customers can enable AppFlow in their customized SCPs as required.
