### ISSUE TITLE
[BUG][Functional] RDGW and Rsyslog Auto-Scaling Groups refer to deprecated Launch Template versions

### ISSUE THREAD

**Issue by joeldesaulniers** [aws-samples/aws-secure-environment-accelerator#1205]
Bug reports which fail to provide the required information will be closed without action.

**Required Basic Info**
- Accelerator Version: release/v1.5.5
- Install Type: Upgrade
- Upgrade from version: N/A

**Describe the bug**
In the Operations account, CloudFormation (CFN) stacks are used to deploy the RDGW auto-scaling group (Operations-Phase5 stack) and the Rsyslog auto-scaling group (Operations-Phase3). Those stacks use templates that hard-code the launch template version to “1”. One customer's launch template version 1 now refers to a deprecated AMI, preventing the auto-scaling group from launching instances in the fleet. I believe the ASEA code base needs to be updated so that those CFN templates refer to a version that is the “latest” launch template. This would allow the auto-scaling groups to use the latest AMI available and NOT a deprecated AMI.

**Failure Info**
- What error messages have you identified, if any: 
The auto-scaling groups fail to launch EC2 instances into the fleet as they're referring to a launch template version that's using a deprecated AMI.
- What symptoms have you identified, if any:
A customer was unable to manage their Managed Active Directory (AD Users and Groups) as their RDGW instance was no longer deployed. It's also likely that som customers won't be able collect syslog logs as their Rsyslog instances will no longer deploy.

**Required files**
N/A - using the standard MAD and Rsyslog configuration available at https://github.com/aws-samples/aws-secure-environment-accelerator/blob/main/reference-artifacts/SAMPLE_CONFIGS/config.example.json.

**Steps To Reproduce**
1. Go to Operation account, click on Auto-Scaling groups.
2. Validate that the auto-scaling groups for RDGW and Rsyslog refer to Launch Template version 1.
3. Launch template version 1 may be referring to a deprecated AMI (can be confirmed by searching for the AMI ID in the AMI catalog).

**Expected behavior**
For the Auto-scaling groups in the Operations account to utilize the "Latest" launch template and not version "1".

**Screenshots**
N/A

**Additional context**
N/A

**Comment by sunilabi** [comment]
+1 looking for an ETA on the fix.
