### ISSUE TITLE
[BUG][SM] z147 - Managed AD fails to deloy to GCWide when three AZs are enabled

### ISSUE THREAD

**Issue by jblaplace** [aws-samples/aws-secure-environment-accelerator#467]
Bug reports which fail to provide the required information will be closed without action.

**Required Basic Info**
- Accelerator Version:  1.2.2
- Install Type: Clean
- Install Branch: Standalone
- Upgrade from version: N/A

**Describe the bug**
Managed AD fails to deploy to CentralVPC_GCWide when third AZ is activated.
"GCWide"  {
              "name": "GCWide",
              "share-to-ou-accounts": false,
              "share-to-specific-accounts": [
                "operations"
              ],
              "definitions": [
                {
                  "az": "a",
                  "route-table": "CentralVPC_GCWide",
                  "cidr2": "100.96.252.0/25"
                },
                {
                  "az": "b",
                  "route-table": "CentralVPC_GCWide",
                  "cidr2": "100.96.252.128/25"
                },
                {
                  "az": "d",
                  "route-table": "CentralVPC_GCWide",
                  "cidr2": "100.96.253.0/25",
                  "disabled": false
                }
              ]
            }

When third AZ is disabled, MAD deploys fine.

**Failure Info**
- MicrosoftADMicrosoftADFC7F6466
Invalid subnet ID(s). They must correspond to two subnets in different Availability Zones. : RequestId: 5bf4f88b-f3f6-4fee-9c4c-a52218e7c138 (Service: AWSDirectoryService; Status Code: 400; Error Code: InvalidParameterException; Request ID: 5bf4f88b-f3f6-4fee-9c4c-a52218e7c138; Proxy: null)

**Required files**
- Please provide a copy of your config.json file (sanitize if required)

**Steps To Reproduce**
1. Enable "az" : d in GCWide (this is a third enabled az)
2. Deploy MAD it will fail
3. See error Invalid subnet ID(s). They must correspond to two subnets in different Availability Zones. 
4. Disable "az": d (leave two az enabled)
5. Deploy MAD is will work

**Expected behavior**
I expect MAD to deploy even when three "az" are enabled.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Brian969** [comment]
Notes:
- MAD only supports 2 az's for its initial deployment
- if we configure subnets in 3 or more az's for the MAD subnets, MAD deployment fails
Fix:
- add a new variable: deployments/mad/azs: ["a","b"] to allow customer to specify MAD az's
- If more than 2 array elements are provided, ignore them (do not fail the SM, log an error in the log files)
- if this new variable is not specified, use the first two az's defined for the specified subnet on the vpc

**Comment by Brian969** [comment]
Shipping in v1.2.5
