### ISSUE TITLE
[BUG] [SM] OUValidation Lambda Times Out During MainStateMachine_sm run

### ISSUE THREAD

**Issue by dyfox1** [aws-samples/aws-secure-environment-accelerator#471]
Bug reports which fail to provide the required information will be closed without action.

**Required Basic Info**
- Accelerator Version:  (eg. v1.1.6) * release/v1.2.1b
- Install Type: (Clean or Upgrade) * clean
- Install Branch: (ALZ or Standalone) * Standalone
- Upgrade from version: (N/A or v1.x.y) * N/A
- Which State did the Main State Machine Fail in: (e.g. Phase 0) * MainStateMachine_sm

**Describe the bug**
(A clear and concise description of what the bug is.)
The OU validation lambda (PIpelineOuValidationHandler) times out after 900 seconds (15 minute lambda timeout) after confirming that OUs have not changed.  This issue happens regularly in both Isengard test labs as well as customer environments.

**Failure Info**
- What error messages have you identified, if any: 
2020-11-18T15:09:38.243Z c8ae0c01-b1a8-4a4f-846c-5dfd60baa02c Task timed out after 901.14 seconds

- What symptoms have you identified, if any:
Pipeline fails, deployments do not proceed

**Required files**
- Please provide a copy of your config.json file (sanitize if required)
[config.txt](https://github.com/aws-samples/aws-secure-environment-accelerator/files/5561321/config.txt)

- If a CodeBuild step failed- please provide the full CodeBuild Log
- If a Lambda step failed - please provide the full Lambda CloudWatch Log
[log-events-viewer-result.txt](https://github.com/aws-samples/aws-secure-environment-accelerator/files/5561318/log-events-viewer-result.txt)

- In many cases it would be helpful if you went into the failed sub-account and region, CloudFormation, and provided a screenshot of the Events section of the failed, deleted, or rolled back stack including the last successful item, including the first couple of error messages (bottom up)

**Steps To Reproduce**
1. Go to Mainstatemachine_sm
2. Click on Start Execution
3. Wait for OU Validation to time out (happens about 50% of the time recently), usually the first re-run fixes the issue

**Expected behavior**
That OU Validation will pass/complete after determining no OU changes have been made

**Screenshots**

**Additional context**

**Comment by Brian969** [comment]
Status: Investigating

**Comment by Brian969** [comment]
Shipping in v1.2.3
