### ISSUE TITLE
[FEATURE] Push CloudWatch Log Agent using Run Command - all instances

### ISSUE THREAD

**Issue by Brian969** [aws-samples/aws-secure-environment-accelerator#489]
This task is dependent on task https://github.com/aws-samples/aws-secure-environment-accelerator/issues/488, which ensures SSM and CWL access policies are properly assigned to all EC2 instances.

Push CloudWatch Log Agent using Run Command - all instances, all accounts

**Comment by archikierstead** [comment]
ASEA not working on new features see README.
