### ISSUE TITLE
[FEATURE] Add support to install ASEA on top of AWS Control Tower

### ISSUE THREAD

**Issue by Brian969** [aws-samples/aws-secure-environment-accelerator#492]
- The ASEA is designed to leverage as many capabilities of native AWS services or offerings as possible
- It has always been planned to add an option to install the ASEA on top of Control Tower, when appropriate (i.e. service available in the Canadian region, assessed for PBMM compliance by the Canadian Cyber Center, etc.)
- We are actively working with the Control Tower team to ensure our roadmaps are aligned and we have a path forward which will allow deploying the ASEA on top of Control Tower, while still allowing customers to meet the Gov't of Canada's PBMM security control requirements
#### BLOCKED: Upgrade from SEA to CT+SEA (requires new CT functionality) - Upgrades from SEA to CT+SEA delayed until 22H1 - will ship without this feature.

**Comment by lkolchin** [comment]
Waiting for this feature to be implemented.
ControlTower implementation is not quite "Production Ready" and aws-secure-environment-accelerator looks much better at least on paper.
Keen to try it when it's ready.

**Comment by Brian969** [comment]
Specific items requiring detailed insight and/or roadmap timelines:
-	How should we reliably detect that Control Tower is deployed in a customer account? (Deployed/Not Deployed)
o	Further, how can we validate Control Tower Status through API (Healthy/Unhealthy)
-	How can we programmatically create a Control Tower managed OU?
-	How can we bypass the Control Tower guardrails for Accelerator deployed Control Tower augmentations?
o	Can we somehow add our roles as bypasses to your SCP's? (without sending CT into unhealthy status)
o	We will NOT modify Control Tower deployed objects as a core principal, but augment them, examples:
	we need to deploy Config recorders in non-CT regions - blocked
	we need to create and enable encryption on a new bucket in the log-archive account to centralize the all other logs not captured by CT, but it must be encrypted (s3:PutEncryptionConfiguration, s3:PutBucketLogging and s3:PutBucketPolicy) - blocked in core OU
-	What is the roadmap and can we prioritize CT reducing its SCP footprint? (common customer ask)
o	i.e. moving to 3 digit SID's, other consolidations in merging SCPs, even if ugly?
-	Status of improving CT CloudTrail support:
o	KMS CMK support? Org trail support? (ability to send to both S3 and CloudWatch Logs)
o	Plans to allow: S3 data plane logging? CT Insights?
-	Plans to enable Config Aggregator?
-	General question - any plans to apply guardrails to the root account?

**Comment by Brian969** [comment]
Planned for next MAJOR (not minor) release i.e. v1.5

**Comment by rverma-nsl** [comment]
Is there any upgrade path from ASEA to ASEA+CT? What are the advantages if any?

**Comment by Brian969** [comment]
****************************
0) CT baseline install Changes
- Create Config Recorder Differently:
   - Create Config Recorder in regions where control tower is not deployed into (not CT regions)
   - Create Config Recorder in all supported regions in management account.
   - Stop Creating Config Aggregator, Control Tower is already deployed one.
   - Use global-options/organizationAdminRole (AWSControlTowerExecution) to createConfigRecorder
- Apply Accelerator Password Policy
- Deploy GuardDuty
- Deploy CloudTrail (To get logs recorded in Log Archive S3 bucket)

1) rename global-options\aws-org-master to global-options\aws-org-management in config file (remove the word master)
2) add a new parameter to the above "section" named "separate-s3-dp-org-trail": true/false, optional, defaults to false, 
   - when this parameter is set to true, create a new/second ORGANIZATION, multi-region, trail
   - use the settings from previous SEA trail deployment used in non-CT SEA version EXCEPT no mgmt events
   - i.e. send to CWL, validation, KMS CMK, our S3 bucket/path, no SNS, all accounts, all regions
   - log group name: /${ACCELERATOR_PREFIX_ND}/CloudTrailS3  ---> i.e. add S3 suffix
   - NO Mgmt events (means insights also not allowed) - Yes to DATA events, all current and future buckets, read/write
   - while I only expect this to be used with CT where we do not create the first trail, someone could turn this on in the non-ct version
3) Extend CloudWatch Metrics and Alarms to support "accounts": ["ALL"]
   - continue to support providing "accounts": ["management"] - for current SEA customers
   - add support for "ALL" to deploy to all accounts in the organization
   - I believe "accounts": [xxx] only supports deploying to the "management" account today
   - enable support for a list of named accounts i.e. "accounts": ["TheFunAccount", "Operations"]
   - continue to use the SNS topic in log-archive for all accounts.
4) Update the codebase to support all 4 account creation methods? (per CT design specs in quip)
   - Account(s) created via orgs, triggers SM after 2mins, SM calls Account Factory Service Catalog item for each new account, then finishes running SM
   - Account(s) created via SEA when SM runs because new account(s) added to config file, calls Account Factory Service Catalog item for each new account, then finishes running SM
   - Account created through CT Enroll account mechanism or by user directly running Account Factory Service Catalog item - we detect the account creation event, see that SC is already running, wait for it to complete, and then run SM

**Comment by Brian969** [comment]
What does setting `"ct-baseline": true` flag do differently:
  - only deploys Config Recorders in the root account and non-ct regions in sub-accounts (as CT covers remainder)
  - does not create Config Aggregator in root account (as CT creates in Security account)
  - uses global-options/organizationAdminRole to createConfigRecorders (or blocked by CT SCPs)
  - Uses ServiceCatalog for account creation (CT Account Factory to properly ingest new accounts into CT)
  - does not create the Org Control Plane CloudTrail (as CT creates account based Control Plane Trails)
 
What settings need to be changed in the config file to install with Control Tower:

- "organization-admin-role": "AWSControlTowerExecution" (MANDATORY)
   - ASEA will be blocked by CT SCPs and CT will be blocked from sub-account access
- "control-tower-supported-regions": [ct regions...]   (MANDATORY)
   - MANDATORY - this allows for no code modifications as CT adds support for additional regions
   - REQUIRES full list of CT supported regions
- "separate-s3-dp-org-trail": true (RECOMMENDED)
   - adds s3 data plane logging back like standalone ASEA deployments
- metrics\"accounts": ["ALL"] (NEEDED)
  - Control Plane trails are now distributed into all accounts, metrics must also be moved to all accounts (instead of root)
- metrics\loggroup-name to "aws-controltower/CloudTrailLogs" (NEEDED)
   - need to target the Control Tower trail log group name
- alarms\"default-accounts": ["ALL"] (NEEDED)
  - Control Plane trails are now distributed into all accounts, alarms must also be moved to all accounts (instead of root)
- Change Core OU to Security OU (for Security, Log Archive and root accounts) (RECOMMENDED)
   - align with AWS multi-account standards
- Add Infrastructure OU (perimeter, shared network, Operations accounts) (RECOMMENDED)
   - align with AWS multi-account standards
- Ensure all ASEA OOB account names match all CT OOB account names (MANDATORY)
