### ISSUE TITLE
[FEATURE] Enhancement - SCP Enhancements 

### ISSUE THREAD

**Issue by Brian969** [aws-samples/aws-secure-environment-accelerator#501]
- Streamline SCP's from 4 files to 3 files
- max file size is 5120 bytes after minified
- move all ASEA protection SCP's together (2 files) and all security SCP's together (1 file)
- move any core-ou only SCP's into a different file
- review overlap with Control Tower SCP's (result: virtually none, all SCP's tightly scoped)
- tweak to support control tower (i.e. add ${ORG_ADMIN_ROLE} to exclusion lists where required)
- determine how to apply SCP's to Security OU, given Control Tower uses 2 files today
  - for the 2 accounts in the security ou (log-archive and security), directly apply the 3rd SCP file at the account level in the ASEA config file.
- NOTE: Today CT uses 2 SCP's on the security OU and 1 on any workload OU.  1 slot is also consumed with the Full Access SCP.

**Comment by charliejllewellyn** [comment]
It would be super helpful to provide 2 sets of SCPs. 1 that is mandatory, i.e. the SCP's required to protect and operate ASEA, 2. recommended SCP's that are a good starter but can be customised without impact. This should make updates much easier for the future without needing to review the updates in any SCPs and merge them. Happy to support this generation if you agree?

**Comment by Brian969** [comment]
Coming in v1.5.0
