### ISSUE TITLE
[FEATURE] Simplify perimeter FW design incorporating AWS Gateway Load Balancer

### ISSUE THREAD

**Issue by Brian969** [aws-samples/aws-secure-environment-accelerator#504]
- dependent on AWS Gateway Load Balancer GA'ing in the Canadian region
******************************************************
## Change Load Balancers to support a new additional type: GWLB
- This will be created in perimeter account
- We will add a second VPC to config config file, named Firewall VPC and Firewall subnet(s)
  - It will be a /23 VPC with two /24 subnets  (could be more az’s for customers)
  - All below from options should be changeable via config file

- Create a GWLB using the ALB config template (GWLB does not need certs, security-policy, scheme, support target-type of both “instance” and “IP”
-  Create the GWLB in a defined subnet and all az’s that exist for that subnet
- Create a TG
  - Instances (allow IP selection as well)
  - Tg_name=config file
  - Leave it Geneve protocol
  - Assoc w/FW VPC
  - HC = TCP (config file)
  - Targets=empty at this point
- Set GWLB listener to above TG
- Create GWLB endpoints in designated subnet (each AZ)
  - Integrated services tab of GWLB
  - i.e. a GWLB is CREATED in a VPC, but then has endpoints dropped into config file defined subnet and AZ’s i.e. it is associated with 2 VPC’s and 2 sets of subnets.
- Update routes to point to GWLB endpoints
  -  Need per az route tables in perimeter VPC
  -  Need to update each rt to point to appropriate endpoint for that az
- Deletion protection on like other ALB’s
- Customer resource - We need to update TGW to allow setting CreateTransitGatewayVpcAttachmentRequestOptions - ApplianceModeSupport: enabled on each attachment (if specified for any attachment).  Since we are adding this custom resource, we should also add the ability to set Ipv6Support: enabled based on config file ON NEW ATTACHMENTS ONLY (as changing this setting not supported) (set in same place as DNSSupport setting)

- We then need to spin up FW’s in this target group, but we want to use an autoscaling group which updates the GWLB target group
- Let’s use a combination of the FW config/code from the current config file PLUS RDGW autoscaling group config/code to come up with a new fw deployment capability
- Create an auto-scaling group
  -  Create a launch template
  - Customer provided AMI
- On-demand instances
  - Instance type
  - Min, max, desired,
  - VPC, Subnets
- Unlike current FW, allow customer to define what is in USERDATA, rather than current fixed fields

### Validate implementation: 
For the auto-scaling group – Checkpoint has [sample](https://supportcenter.checkpoint.com/supportcenter/portal?eventSubmit_doGoviewsolutiondetails=&solutionid=sk111013#Auto%20Scaling%20Group) CFN templates with GWLB support - use them as a baseline example of how to configure/setup.  On that page, scroll to: Gateway Load Balancer (GWLB) Auto Scaling Group - likely the second example is closest to what we want to do.  Ensure also continues to support Fortinet capabilities.

**Comment by ActionAnalytics** [comment]
Hi Julian here from BC Gov DevOps & Cloud Services team.  We'd really like this feature to be available in the SEA so that we can select a CheckPoint brand firewall and have it deployed similar to how the Fortigate ones are.

**Comment by chkp-jeffkopko** [comment]
We are interested in working with AWS to incorporate a Checkpoint Secure Gateway into SEA for customers to choose as a security provider.  We have several customers that have expressed interest

**Comment by ActionAnalytics** [comment]
How is this progressing?  Any updates or blockers we should know about?  Thanks again, very much looking forward to this.

**Comment by Brian969** [comment]
Hoping it makes the next major release i.e. v1.5
