### ISSUE TITLE
[FEATURE] Add option to leverage AWS Network Firewall Service in perimeter

### ISSUE THREAD

**Issue by Brian969** [aws-samples/aws-secure-environment-accelerator#505]
Add option to leverage AWS Firewall Service
- Dependent on AWS Firewall Service GA'ing in the Canadian region
***********************************************

Design principal: Add to any VPC just like a NATGW

### Current NATGW Config – EXAMPLE WITH SINGLE AZ:
```"vpc": [
 {
  "name": "Sandbox",
...
  "natgw": {
    "subnet": {
      "name": "Web",
      "az": "a"
    }
  },
  "subnets": [
    {
      "name": "Web",
...
  ],
  "route-tables": [
    {
      "name": "SandboxVPC_Common",
      "routes": [
        {
          "destination": "0.0.0.0/0",
          "target": "NATGW_Web_azA"
        } ] } ]
```

### Current NATGW Config - EXAMPLE WITH PER AZ NATGW 

```"natgw": {
    "subnet": {
      "name": "Web"             		<----- No az’s means all az’s with subnets
    }
...
  ],
  "route-tables": [
    {
      "name": "SandboxVPC_a",
      "routes": [
        {
          "destination": "0.0.0.0/0",
          "target": "NATGW_Web_azA"
        } ] },
    {
      "name": "SandboxVPC_b",
      "routes": [
        {
          "destination": "0.0.0.0/0",
          "target": "NATGW_Web_azB"
        } ] } ]
```
### New NFW Config Summary:

Add a new identical option named nfw instead of natgw to config 
-	New section like “natgw”:, renamed to: “nfw”:
-	Supports one specific az, multiple specific az’s, all az’s w/subnets like above
-	Route tables support routing to the NFW replacing NATGW above w/”NFW_Web_azA”
o	NFW_Subnet_AZ
- Add new policy object with policy name and file path
   - We should push something into this first policy to allow traffic/basic oob functionality (yaml attached)
 
### New partial sample config file:
```"vpc": [
 {
  "name": "Sandbox",
...
  "natgw": {
    "subnet": {
      "name": "Web"
    }
  },
  "nfw": {
    "subnet": {
      "name": "App",
       "az": "a"
    },
    “policy”: {
         "name": "my-first-rule", 
          "path": “nfw-sample-rule.yaml”
     }
  },
…
  "route-tables": [
...
        {
          "destination": "10.0.0.0/8",
          "target": "NFW_App_azA"
        }
      ]
    },
    {
      "name": "SandboxVPC_a",
      "routes": [
        {
          "destination": "0.0.0.0/0",
          "target": "NATGW_Web_azA"
        }
      ]
    },
    {
      "name": "SandboxVPC_b",
      "routes": [
        {
          "destination": "0.0.0.0/0",
          "target": "NATGW_Web_azB"
        }
      ]
    },
,
    {
      "name": "SandboxVPC_TGWa",
      "routes": [
        {
          "destination": "0.0.0.0/0",
          "target": "NFW_App_azA"
        },
        {
          "destination": "10.0.0.0/8",
          "target": "TGW"
        }
      ]
    },
    {
      "name": "SandboxVPC_TGWb",
      "routes": [
        {
          "destination": "0.0.0.0/0",
          "target": "NFW_App_azB"
        },
        {
          "destination": "10.0.0.0/8",
          "target": "TGW"
        }  ]  }  ]
```

### Challenge: How do we route inbound traffic?
- ALB does not support DNS targets, backend ALB only has DNS address

#### Part 1 - New Customer populated Perimeter account DDB Table:
- perim-alb-identifier – i.e. Public-DevTest-perimeter (mandatory)
  - alb stored in: /ASEA/lelb/alb/1/name
- public-hosts – i.e. [www.briantest.ca, briantest.ca] (mandatory)
- public-paths – i.e. brianapp1 (optional)
- target-alb-dns-name: i.e. internal-Core-mydevacct1-alb-882478976.eu-west-1.elb.amazonaws.com
   - stored in /ASEA/elb/alb/1/dns
- target-group-name – i.e. briantest
- target-group-port: “HTTPS:443”
- target-port: 443 
- target-alb-dns-addresses: [list of many ip addresses from last alb tg UPDATE]
   - ???acm cert???  what do we need to handle? anything?

#### Part 2 - Create a new perimeter Lambda, triggered every 1min
- scans the ddb table
- updates each alb with appropriate rules and target groups
- updates target group addresses by adding new addresses and then removing old addresses
  - do not replace list or remove first, must add then remove

Lambda REQUIREMENTS:
If new account, create new target group (up to 100 per alb) ---> place in 2nd Lambda triggered on DDB stream?
-	TG, Ip Based, Name, HTTPS, 443, local VPC, HTTP1, /health-check, https, 
-	Name=host+path replacing special characters and  trimming to X
Other private addresses, 1.1.1.1, 443, 2.2.2.2, 443, etc, etc
-	populate based on nslookup of backend alb to a max of 10
-	do not set TG stickiness
Forward to: IP based Target Group (up to 99 TG per ALB)
-	Based on host/path combo to specific TG
-	Do NOT set group stickiness (only 1 group)
-	Rules with paths – add to top
-	Rules with urls only add to bottom

Default  rules should point to a target group defined by a DEFAULT DDB entry as well
Defined by placing ‘DEFAULT’ in public-host field

New account based config file variable: deploy-alb-stitching: true
- causes DDB tables and 2 Lambda's to be properly deployed

#### PART 3: ENABLE WAF ON existing ALB (if param set)

New ALB Fields:
- waf: true
- waf-acl-name: “Central-ALB”

Separately define 
- waf-acls {
   - Name: ”Central-ALB”
   - Enable-logging to central log-archive bucket
   - waf-rules: objects? Array? Other?
          - AWS-AWSManagedRulesAmazonIpReputationList
          - AWS-AWSManagedRulesAnonymousIpList
          - AWS-AWSManagedRulesCommonRuleSet
          - AWS-AWSManagedRulesKnownBadInputsRuleSet
          - AWS-AWSManagedRulesLinuxRuleSet
          - AWS-AWSManagedRulesPHPRuleSet
          - AWS-AWSManagedRulesUnixRuleSet
          - AWS-AWSManagedRulesSQLiRuleSet
          - AWS-AWSManagedRulesWindowsRuleSet
          - AWS-AWSManagedRulesWordPressRuleSet

**Comment by rverma-nsl** [comment]
Is there any WIP code which we can refer? Are we having development in private forks and then those changes cherrypicked into this project?

**Comment by Brian969** [comment]
Hi Rohit,

Unfortunately, due to some internal process changes, yes, we had to pull development internal.

No we are not "cherry picking" features to publish - all features/functionality/fixes will continue to be published, but as part of a release cycle.  We are working towards v1.5.0 which will hopefully include the features both "In Review/Test" and "In-Progress".  Should be code complete EOM and then we will need to see what the new release process looks like...  I'll add some details as to design specs for this one - this feature is 60% through active development.

**Comment by Brian969** [comment]
To create the network firewall, in the config file, modify a vpc to contain the following:

<details><summary>Click to expand</summary>

``` vpc": [
        {
          "deploy": "local",
          "name": "firewall",
          "cidr": [
            {
              "value": "10.0.0.0/19",
              "pool": "main",
              "size": 19
            }
          ],
          "region": "us-west-2",
          "use-central-endpoints": true,
          "flow-logs": "BOTH",
          "dns-resolver-logging": true,
          "igw": true,
          "alb-forwarding": true,
          "nfw": {
            "subnet": {
              "name": "external"
            },
            "policy": {
              "path": "nfw/nfwPolicy.json",
              "name": "example-nfw-policy"
            },
          },
          "subnets": [
            {
              "name": "external",
              "definitions": [
                {
                  "az": "a",
                  "route-table": "external_a",
                  "cidr": {
                    "value": "10.0.0.0/22",
                    "pool": "main",
                    "size": 22
                  }
                },
                {
                  "az": "b",
                  "route-table": "external_b",
                  "cidr": {
                    "value": "10.0.4.0/22",
                    "pool": "main",
                    "size": 22
                  }
                }
              ]
            },
            {
              "name": "internal",
              "definitions": [
                {
                  "az": "a",
                  "route-table": "internal",
                  "cidr": {
                    "value": "10.0.12.0/22",
                    "pool": "main",
                    "size": 22
                  }
                },
                {
                  "az": "b",
                  "route-table": "internal",
                  "cidr": {
                    "value": "10.0.16.0/22",
                    "pool": "main",
                    "size": 22
                  }
                }
              ]
            },
```
Example Route: 

```              "routes": [
                {
                  "destination": "0.0.0.0/0",
                  "target": "NFW_external_azA"
                }
              ]
```

</details>

Once completed, the sample firewall config will need to be placed in the global-config bucket 
[nfwPolicy.json](https://github.com/aws-samples/aws-secure-environment-accelerator/files/6666373/nfwPolicy.txt)

To test the functionality of the alb-ip-forwarding, you must have an ALB listener rule arn for an external ALB arn. There are also limitations to what IP addresses can be assigned to the target group [ALB IP limitations](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html)

Here is a sample dynamodb item that can be used to generate an ALB IP forwarding target group [putItem.txt](https://github.com/aws-samples/aws-secure-environment-accelerator/files/6666375/putItem.txt).
 This item should be written to the table generated by the cdk deployment. There must be an existing listener arn available on an ALB inside an account that the listener rules can be attached to.

**Comment by rverma-nsl** [comment]
Is this merged ?

**Comment by Brian969** [comment]
No, coming in v1.5.0, this PR is currently in first round of testing. Hoping to get v1.5.0 code complete for mid-next week, then need to push through some security reviews, and more thorough testing, etc. before publishing.  Sorry for the delays, several weeks behind where we'd hoped to be for this release.
