### ISSUE TITLE
[BUG][Functional] Duplicate entries for account name being to the config file by the accelerator

### ISSUE THREAD

**Issue by rjjaegeraws** [aws-samples/aws-secure-environment-accelerator#513]
Bug reports which fail to provide the required information will be closed without action.

**Required Basic Info**
- Accelerator Version: v1.2.2
- Install Type: Both
- Install Branch: Standalone
- Upgrade from version: N/A

**Describe the bug**
Workload accounts created by the UI or API/CLI and moved into a SEA managed OU  has entries dynamically added to the config file. A spelling typo '' is causing erroneous json attributes to the config file.

Example:
 "myworkloadaccount": {
      "account-name": "....",
      **"accoount-name"**: "...t"
    },

**Failure Info**
- What error messages have you identified, if any: None
- What symptoms have you identified, if any: None

**Required files**

**Steps To Reproduce**
1. Create an AWS Account
2. State Machines Runs
3. Move it to a managed OU

**Expected behavior**

Only see "account-name" attribute.

**Screenshots**

**Additional context**

**Comment by Brian969** [comment]
@naveenkoppula - can you please prioritize this fix?  Needs fix in both mandatory and workload accounts section of "Move-account...".

**Comment by Brian969** [comment]
Shipping in v1.2.3
