### ISSUE TITLE
[OTHER] Items requiring SDE investigation

### ISSUE THREAD

**Issue by Brian969** [aws-samples/aws-secure-environment-accelerator#519]
- ~~*investigate* process to create new account directly in a sub-ou using SM (i.e. /Dev/My-sub-ou/account)~~ - non-issue
  - ~~this is working, simply a mis-understanding~~
- review mock test cases and snapshot inclusions 
  - some updates unnecessarily require snapshot updates, can we refine?
- ~~remove missed/remaining tslint references (do this with the CDK upgrade PR needed for z125)~~ - Done in PR#520
  - ~~SSM branch was development when tslint was implemented and was missed, tslint.json in root of repo, others?~~
- ~~investigate multi-part config files (may be issues when used within a list/array)~~ - Done in PR#521

**Comment by naveenkoppula** [comment]
Current pseudo code for Unsupported property changes in resource.

- Read Config from ``` reference-artifacts/config.example.json ``` and use for cdk synth
- filter following resourceTypes for validating unsupported property changes
  [ 'AWS::Budgets::Budget', 'AWS::DirectoryService::MicrosoftAD', 'AWS::EC2::Instance', 
    'AWS::EC2::TransitGateway', 'AWS::ElasticLoadBalancingV2::LoadBalancer', 
    'AWS::S3::Bucket', 'AWS::SecretsManager::Secret', 'AWS::SecretsManager::ResourcePolicy']
- perform jest snapshot testing, If no previous snapshot file exists then create one and validate using same file for next execution

Looks good and working as expected.

**Comment by Brian969** [comment]
Thanks Naveen!

**Comment by naveenkoppula** [comment]
We did change snapshots for configuration change which is not related to unsupported resources for commit https://github.com/aws-samples/aws-secure-environment-accelerator/commit/5de154e807c500119c7e7042eab5f0bdf4e03aa4.

Reason is we did remove some of ``` interface-endpoints ``` which lead to removal of  ``` SharedNetworkPhase2VpcEndpoints3 1 ``` stack entry from existing snapshot and that is not actual unsupported change since that is an empty array.



``` eg: exports[`there should not be any unsupported resource changes for AWS::Budgets::Budget: SharedNetworkPhase2VpcEndpoints3 1`] = `Array []`; ```

**Comment by Brian969** [comment]
Shipping in v1.2.4
