### ISSUE TITLE
[ENHANCEMENT] Move to org permission from per account permissions

### ISSUE THREAD

**Issue by Brian969** [aws-samples/aws-secure-environment-accelerator#534]
**Required Basic Info**
- Accelerator Version: v1.2.3

**Describe the solution you'd like**
- today the log-archive s3 bucket policies, log-archive KMS keys, and SSM automation documents are updated with permissions per account
- do we have any other permissions which require access from all accounts in the organization? (CWL?)
- switch to using organization permissions, rather than updating the policies per account
- do any objects not support leveraging org level permissions?

**Why**
- We will run out of space in each of the respective policies as we scale to 1000's of accounts

**Comment by naveenkoppula** [comment]
Did get it worked with ``` principal: "*" ``` but got error in AWS KMS console and everything works as expected.

error: ``` "*" should be object ```

Able to use ``` principal: { "AWS": "*" } ``` by updating manually in AWS KMS console but when we try to deploy it through cloudformation using CDK got error saying invalid policy document, But there is not error in console.

error: ``` Policy contains a statement with one or more invalid principals. (Service: Kms, Status Code: 400, Request ID: 6426d0a0-3eda-4a15-ad60-4b74b9aec331, Extended Request ID: null) ```

**Comment by Brian969** [comment]
Hey 
- the "config" bucket looks good.
- looks like the AES bucket was missed for org permissions???
- what's the getobject permission for - I'd like to drop it...

**Comment by Brian969** [comment]
- This will ship in v1.3.0
