### ISSUE TITLE
[BUG][Functional] AWS Account Names beginning with a number will fail the State Machine

### ISSUE THREAD

**Issue by rjjaegeraws** [aws-samples/aws-secure-environment-accelerator#538]
Bug reports which fail to provide the required information will be closed without action.

**Required Basic Info**
- Accelerator Version: v1.2.2
- Install Type: Upgraded
- Install Branch: Standalone
- Upgrade from version: v1.1.9

**Describe the bug**
The Main StateMachine fails in Phase1 if the AWS Account name starts with a number.

**Failure Info**
- What error messages have you identified, if any: 
Error: Resolution error: Logical ID must adhere to the regular expression: /^[A-Za-z][A-Za-z0-9]{1,254}$/, got ....

CloudFormation LogicalID have rules for a valid value: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html

- What symptoms have you identified, if any:

Failed state machine where subsequent runs fail. 

**Required files**
- Please provide a copy of your config.json file (sanitize if required)

**Steps To Reproduce**
1. Create an AWS Account that starts with a number.
2. Move the AWS Account into a SEA 'Sandbox' managed OU. (unknown if 'Sandbox' is part of the issue)
3. Watch the Main State Machine.

**Expected behavior**
If the AWS Account name is supported by its create API, the SM should be able to handle it.

**Screenshots**

**Additional context**

**Comment by Brian969** [comment]
@rjjaegeraws - Hey - can you provide more information on this error?  We can't find anywhere in the codebase where we are generating the logical ID using the account name and not removing the number (i.e. everything is pascal case).  It would help to have the rest of the error/the specific logical ID that had an issue so we can find your conflict.  We did run the Accel with an account starting with a number without any issue.

**Comment by Brian969** [comment]
Sample logical ID: Full error - Error: Resolution error: Logical ID must adhere to the regular expression: /^[A-Za-z][A-Za-z0-9]{1,254}$/, got '14aebrSandbox37Fa2APhase1VpcStackSandbox6175CBB6Ref'.```

**Comment by naveenkoppula** [comment]
``` 14aebrSandbox37Fa2APhase1VpcStackSandbox6175CBB6Ref ``` is this found in Phase1 stack in account whose account name starts with number? I did try running with default configuration file which has VPC in sandbox ou, but didn't find this format of logical id and successfully executed.

@rjjaegeraws, please provide configuration file for which you got this error.

**Comment by Brian969** [comment]
We have triple validated that this is not an issue with account names starting with numbers.  While we would really like to find and remediate this issue, if we do not get more information to assist in finding the source of this failure, we will need to close this ticket.

**Comment by rjjaegeraws** [comment]
Understand. I've been unable to get additional information at this point.

**Comment by Brian969** [comment]
Closing issue.  Feel free to re-open if more information becomes available.  Thanks!
