### ISSUE TITLE
[BUG][OTHER] S3 'consistency' Issues

### ISSUE THREAD

**Issue by Brian969** [aws-samples/aws-secure-environment-accelerator#541]
**Required Basic Info**
- Accelerator Version:  v1.2.3
- Install Type: Clean
- Install Branch: Standalone
- Which State did the Main State Machine Fail in: Verify Files

**Describe the bug**
- we are running into occasional issues where the files that exist in s3, are not found
  - by verification logic, or ec2 instances attempting to access them
- In this case, "Verify Files" fails the SM because a file fails to exist in S3 which was successfully copied in Phase0
- screenshots shows the file does actually exist
- screenshots show the file creation timestamp is before the verify file failure timestamp
- screenshots show an aws s3 ls using the exact cut/paste filename succeed
- Additionally, we have had occasionally similar issues with the firewall config file failing to be read by the firewalls at boot/userdata from s3 - files are all proven to exist in this case as well
- thought it was a timing eventual consistency issue, but s3 is now strongly consistent
- rerun of the state machine succeed with no changes/updates

**Failure Info**
- Screenshot of error, including timestamp:
![image](https://user-images.githubusercontent.com/56414362/102515567-e8fc9100-405b-11eb-9a33-4503c2c7346e.png)

- screenshot of aws s3 ls on exact cut/paste filename output, including timestamp:
![image](https://user-images.githubusercontent.com/56414362/102515718-15b0a880-405c-11eb-911f-ca880a930c97.png)

- screenshot of s3 console info of file:
![image](https://user-images.githubusercontent.com/56414362/102515792-2c56ff80-405c-11eb-9374-ab3068fe097e.png)

**Please validate**
- please validate all accelerator verify files logic is accurate and up
- please check for cdk/sdk library updates that may include a fix in later release
- if nothing found after above, ticket the s3 service team and tag me

**Comment by naveenkoppula** [comment]
We are using ``` BucketDeployment from @aws-cdk/aws-s3-deployment ``` package to copy local files to S3. It will use ``` aws s3 sync /tmp/tmpyl8wb2bx/contents s3://pbmmaccel-master-phase0-configcacentral1-xxxxx/ssm-documents ``` command to make copy.


To verify files we just do ``` s3.getObjectBody ``` api call in verifyFiles step lambda function

everything happens in sequenctial order and synchronus calls.

**Comment by Brian969** [comment]
ISSUE:
- According to the AWS public documentation, bucket configurations have eventual consistency. As per https://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html#ConsistencyModel, ```"If you enable versioning on a bucket for the first time, it might take a short amount of time for the change to be fully propagated. We recommend that you wait for 15 minutes after enabling versioning before issuing write operations (PUT or DELETE) on objects in the bucket."```
- we create the bucket, immediately enable versioning, write new files, and then try to verify their existence
- this puts the bucket into eventual consistency mode until the versioning bucket configuration become consistent
- this issue does not exist for Accelerator upgrades or subsequent executions as the bucket will be strictly consistent
- we do not want to add long delays to the installation process, but we need consistent and reliable deployment capabilities
SOLUTION:
- Update codebase to:
- during install, stop turning on bucket versioning on buckets we read from during the accel execution (i.e. config buckets in root, config bucket in perimeter (deployments section), other buckets) during the current bucket creation process
- In an existing step near the end of the SM execution, add turning 'bucket versioning on' to all deployed buckets

**Comment by Brian969** [comment]
Shipping in v1.2.5
