### ISSUE TITLE
[FEATURE] Read-only access to Log Archive for IAM roles

### ISSUE THREAD

**Issue by BrianFanning** [aws-samples/aws-secure-environment-accelerator#543]
**Required Basic Info**
To properly assess the enhancement request, we require information on the version of the Accelerator you based this request upon:
- Accelerator Version:  1.2.3
- Install Type: (Clean or Upgrade) Clean/Upgrade
- Install Branch: (ALZ or Standalone) Standalone
- Upgrade from version: (N/A or v1.x.y) N/A

**Is your feature request related to a problem? Please describe.**
IAM roles created through the ASEA can use the 'ssm-log-archive-access' flag to give a role read + write access to the Log Archive account. However there is no equivalent read-only version of this flag. I'm currently trying to deploy an SIEM solution which uses a Lambda function to fetch objects from the Log Archives centralized logging bucket. The Lambda role needs read-only access to the bucket. Currently my only option is to give the role 'ssm-log-archive-access' which is too permissive.

**Describe the solution you'd like**
An equivalent of the ssm-log-archive-access flag, but for read-only access to the Log Archive centralized logging bucket. The flag could be called 'ssm-log-archive-read-only-access', and potentially rename the existing 'ssm-log-archive-access' flag to 'ssm-log-archive-full-access' to clearly differentiate the two flags. 

**Describe alternatives you've considered**
For my use case I could use the existing 'ssm-log-archive-access' flag, but I'd be breaking principle of least privilege. If the Lambda function is compromised, files in the log archive could be deleted/modified.

**Comment by Brian969** [comment]
Looks good, I look forward to the enhancement!

**Comment by Brian969** [comment]
Please tweak per Naveen's comments on PR.

**Comment by Brian969** [comment]
Shipping in v1.2.5
