### ISSUE TITLE
[BUG][Functional] Cloud9 Fails to create

### ISSUE THREAD

**Issue by rjjaegeraws** [aws-samples/aws-secure-environment-accelerator#557]
Bug reports which fail to provide the required information will be closed without action.

**Required Basic Info**
- Accelerator Version:  v1.2.2
- Install Type: (Clean or Upgrade) Clean
- Install Branch: (ALZ or Standalone) Standalone
- Upgrade from version: (N/A or v1.x.y) v1.1.9

**Describe the bug**
(A clear and concise description of what the bug is.)
Attempting to launch a Cloud9 instance with SSM fails. 

**Failure Info**
- What error messages have you identified, if any: 

CloudTrail reports the following error:

errorCode | AccessDenied
-- | --
errorMessage | User: arn:aws:sts::866470196944:assumed-role/AWSServiceRoleForAWSCloud9/AWSCloud9Workspace-866470196944 is not authorized to perform: kms:GenerateDataKeyWithoutPlaintext on resource: arn:aws:kms:ca-central-1:866470196944:key/57b68747-d552-4f38-8cd3-cb42727dcde5

- What symptoms have you identified, if any:
The Cloud9 CFN fails with the following error: Instance i-0fc58d2a8f70b6009 failed to stabilize. Current state: shutting-down. Reason: Client.InternalError: Client error on launch

**Required files**
- Please provide a copy of your config.json file (sanitize if required)

**Steps To Reproduce**
1. Go to workload account within the SEA
2. Attempt to launch a Cloud9 environment using SSM

**Expected behavior**
The Cloud9 launches and that it is accessible.

**Screenshots**

**Additional context**

There are two problems:
1) The Cloud9 Environment needs the correct access to the EBS key specified by the default account encrypt settings. This will fix the CFN from failing during the Cloud9 deployment.

2) The Cloud9 Environment needs the correct access to the SSM key. This will fix the user experience of being unable to connect to the instance once the previous problem is resolved.

See the very bottom of this page for details on the expected Key Policy:
https://docs.aws.amazon.com/cloud9/latest/user-guide/move-environment.html

**Comment by Brian969** [comment]
As Cloud9 is not covered under any compliance program (ISO, SOC, etc.), it was added to the denied services list in the default set of SCP's in the latest Accelerator version (v1.3.4).  Should a customer wish to use cloud9 within the ASEA, they will now need to override the default SCP's with a custom SCP to enable the service.  Customers can then have two options: 1) use the "SSH Connection" method (using the [Cloud9 Installer](https://docs.aws.amazon.com/cloud9/latest/user-guide/installer.html) to stand-up a Cloud9 instance within the ASEA, or 2) in any one specific account override the default EBS KMS to a new CMK and set a policy appropriate for use with Cloud9 and use one of the other mechanisms.
