### ISSUE TITLE
[ENHANCEMENT] Enable CodeBuild caching for Installer step in CodePipeline

### ISSUE THREAD

**Issue by rverma-nsl** [aws-samples/aws-secure-environment-accelerator#658]
**Required Basic Info**
To properly assess the enhancement request, we require information on the version of the Accelerator you based this request upon:
- Accelerator Version:  1.26.a, master

**Describe the solution you'd like**
Modify the codebuild pipeline to add the caching https://docs.aws.amazon.com/codebuild/latest/userguide/build-caching.html to reduce the build time

**Describe alternatives you've considered**
None available

**Comment by rverma-nsl** [comment]
Hi @Brian969 

Thanks for quick response. This is more about the Accelerator update pipeline. Every release change of accelerator takes 1/2 hour of codebuild run time, I assume cause its building without any cached dependencies. 

Would help in development of accelerator itself.

**Comment by Brian969** [comment]
Wow - I just manually tested making that change and it sped up the Codebuild Installer stage (for an upgrade only) by over 50%!  Great suggestion.  We are also exploring replacing webpack with esbuild to further drop the Installer time.

THANKS!

**Comment by rverma-nsl** [comment]
Hi Biran,

Good to see. I would recommend to build the cdk runtime also as micro containers i.e generate different smaller images in the first phase. This can also help in 2 ways
1. Build and update only that part of ASEA which is changed as per a logical segregation, could be as per your module convention. However I would strongly suggest to build runtime as independent.
2. Codebuild runs would be faster since they now have to pull smaller images.
3. To further reduce the image sizes you can use something like gcr.io/distroless/nodejs:12, the based container is 93 Mb as against to bitnami one which is 670MB. I assume this if implemented correctly can make the whole experience snappier :)

**Comment by rverma-nsl** [comment]
I understand the irony of recommending a google tech to aws

**Comment by rverma-nsl** [comment]
Hi Brian,

Wondering if there is a developer guide for faster feedback i.e from adding a cdk asset to applying that via step function.
The current build and release workflow is extremely slowly cause of the need to build whole project 2 times. Even we are not passing the build cache as omitted here https://github.com/aws-samples/aws-secure-environment-accelerator/blob/fe4b5dfea7ff5c437028acd937312ad87526e855/src/lib/cdk-accelerator/src/codebuild/cdk-deploy-project.ts#L48. 

Is there a recommended way to proceed while adding new constructs and apply them via step functions which doesn't involve building and awaiting 40 min for every change :) ?

**Comment by naveenkoppula** [comment]
> Hi @Brian969 ,
> 
> Wondering if there is a developer guide for faster code feedback i.e from adding a cdk asset to applying that via step function.
> The current build and release workflow is extremely slow, I believe its because of the need to build whole project 2 times. Even we are not passing the build cache as omitted here
> 
> https://github.com/aws-samples/aws-secure-environment-accelerator/blob/fe4b5dfea7ff5c437028acd937312ad87526e855/src/lib/cdk-accelerator/src/codebuild/cdk-deploy-project.ts#L48
> 
> .
> Is there a recommended way to proceed while adding new constructs and apply them via step functions which doesn't involve building and awaiting 40 min for every change :) ?
> 
> Also since most of the lambda functions have auto-generated name, everytime we update the step functions, it push to recreate all lambda functions.
> 
> Can we omit that by assiging a static name to lambdas?

Hi @rverma-nsl ,

All CDK constructs will go into Phases, 
To continue with local development please follow 
https://github.com/aws-samples/aws-secure-environment-accelerator/blob/main/docs/developer/developer-guide.md#483-phase-stacks

**Comment by rverma-nsl** [comment]
`outputs.json based on outputs.json in the Accelerator configuration bucket` part of the document is little confusing since it exists in dynamodb phasewise outputs.

Also wouldn't it be great if we can read directly from dynamodb in the first place :)

**Comment by Brian969** [comment]
Good catch - at one time we had the outputs stored in S3 and we missed updated this here in the docs, will be fixed in PR #667.

(...and Yes :-))

**Comment by rverma-nsl** [comment]
@Brian969 / @naveenkoppula  have you guys considered using microsoft's rush for this, to support incremental builds. Currently I am observing that even with caching its not effective.

2nd thing is the whole build methodology in the first place, looking for your inputs on the same. We are building the same project two times
1. Within codebuild
2. Within dind (Docker build) as part of 1. 

Rather than that can't we build the docker image directly from the build result of 1st?

**Comment by Brian969** [comment]
Shipping in v1.5.0 (version # could change)
