### ISSUE TITLE
[BUG][Deployed Functionality] Removing a region from SEA management does not uninstall the SEA from the region

### ISSUE THREAD

**Issue by rverma-nsl** [aws-samples/aws-secure-environment-accelerator#660]
**Describe the bug**
Initially we deployed the ASEA with default config which actually deployed it in all regions, even though we have supported regions as all. We although provided specific region in each account though like `central-security-services`. 

This has two major impacts
1. We got so many iam roles in each region
2. We got cloudformation Phase0 and cdktoolkit stacks creates in all regions enabing config recorders everywhere.

**Failure Info**
We re ran the ASEA with removed supported regions but found that the stacks not get deleted.

**Additional context**
It might be a good idea to by default omit cross region resources like IAM from config recorders in other regions apart form home region.

**Comment by Brian969** [comment]
Hi rverma-nsl,
- While you may be blocking the use of extra regions, security best practice is to turn on logging and monitoring in all Enabled AWS regions (17 by default).  If the blocks are working, the logs will be empty and cost nothing or almost nothing.  If they are somehow disabled and someone performs activities in those regions, you are a) notified immediately and b) have the data to determine who did what and when and take appropriate actions.
- If you started with 16 regions and then changed your config to 2 regions and we left everything enabled, that is likely a defect that we should investigate and fix.  Appreciate you taking the time to report the issue!

**Comment by rverma-nsl** [comment]
I would like to propose an alternative approach here, it would be nice if we can create a scp which Deny all operations on all regions and thus enforces that all regions are also secured. I am totally in favour of enabling security controls on all regions in use.

Something like this https://gist.github.com/rverma-nsl/299a5fa9b44261c0914bdcf72d30b618

**Comment by Brian969** [comment]
Hi rverma-nsl,
Yes, we already have an scp which Deny all operations on all regions - see [here](https://github.com/aws-samples/aws-secure-environment-accelerator/blob/main/reference-artifacts/SCPs/ASEA-Guardrails-Sensitive.json).  

In security, Defense in Depth is important.  It's critical not to rely on a single security control.  What does it hurt to have another layer of security and the ability to debug an issue when one of your administrators removes the SCP and does something they were not allowed?

I don't expect to convince you, and that's the beauty of this solution.  It's completely customizable.  While many of my customers demand multiple layers of security, I also have customer like yourself that are comfortable with a different set of security controls.  On a new deployment, simply specify the one or two regions you want secured in `supported-regions` section of the config file, and only those regions will be guard railed, as you desire.  

It's unfortunate that you initially deployed with the full config and you found a defect which prevents automating the removal of some of those controls, but if its important to you, you can manually remove those extra stacks (in reverse order).  

Hope this helps!

**Comment by rverma-nsl** [comment]
Hi Brian,

Thanks for pointing out that scp. Can you help me understanding the application of the same, it seems this is something what I want to. I am failed to understand the ADDL_REGIONS_B & ADDL_REGIONS_A analogy here and assuming that ADDL_REGIONS_B takes input as a list too.

Thanks :)

**Comment by Brian969** [comment]
To enable customers to customize the regions in the SCP files without needing to manually supply new SCP files in there input bucket (causing extra effort during each upgrade), we added those variables, which are defined in the top of the main config file.
```json
  "replacements": {
    "addl_regions": {
      "a": ["${HOME_REGION}"],
      "b": ["${HOME_REGION}", "${GBL_REGION}"],
      "c": ["${HOME_REGION}", "${GBL_REGION}", "us-east-2", "us-west-1", "us-west-2"]
    },
```
Whatever these are defined as in the main config file, will be replaced inside the scp at deployment time.  If you are installing in the ca-central-1 region that is your home region, based on what is defined in the sample config files (above), ADDL_REGIONS_A resolves to ca-central-1, ADDL_REGIONS_B resolves to ca-central-1, us-east-1, and ADDL_REGIONS_C resolves to "ca-central-1", "us-east-1", "us-east-2", "us-west-1", "us-west-2".  GBL_REGION is always us-east-1.  You can change what these resolve to as you see fit and they will be reflected in the deployed SCP (and other places used, as these variables are also used to search/replace within the config file itself).

If you do not like the provided SCP, you can always simply replace it by placing an identically named file in you input bucket in the SCP folder.

Hope this helps/clarifies!

**Comment by Brian969** [comment]
- After thinking about this "issue", I went back and reviewed some of our original design notes
- Implementing this ticket would essentially require creating a fully automated set of cleanup and uninstall scripts
- this is not an easy task and an extensive amount of work (out of scope of our goals) and not the best investment of our limited resources at this time
- we decided that automatically disabling the deployment of guardrails in any region post deployment was not in scope of the solution
