### ISSUE TITLE
[BUG][Functional]  Introduce some cleanup and optimize no of iam roles

### ISSUE THREAD

**Issue by rverma-nsl** [aws-samples/aws-secure-environment-accelerator#663]
ASEA should embrace reusability of iam roles and should cleanup roles required for accelerator run. 
 
**Required Basic Info**
- Accelerator Version:  1.26-a, main
- Install Type: First clean then pointed ot main branch
- Upgrade from version: 1.26-a to main

**Describe the bug**
In my operation account, I endup with over 90 Admin access roles like these
`arn:aws:iam::xx:role/cdk-nsl-cfn-exec-role-xx-ap-northeast-1.`

This happened as a side effect of  https://github.com/aws-samples/aws-secure-environment-accelerator/issues/660

I recommend if we are going to create multiple roles with have same access, then why not reuse the existing PipelineRole with added trust permissions. Infact all the ASEA provisioned accounts have more than 35-40 iam roles.

**Failure Info**
No failures, expected

**Required files**
https://gist.github.com/rverma-nsl/b3e390d4430972eff955c11e9bfd4e10

**Steps To Reproduce**

**Expected behavior**
Limited reusable roles. Even better if we can have more human friendly names sk

**Screenshots**
<img width="1440" alt="Screenshot 2021-03-12 at 10 39 02 PM" src="https://user-images.githubusercontent.com/80032502/110973895-ddcbaf80-8383-11eb-89a1-1d837e1992ed.png">

**Comment by Brian969** [comment]
Hi rverma,

NOTE: `main` branch is always a work in progress.  We do not support customer installs off the main branch, and encourage customers to stick with official releases.  Just a friendly warning to proceed at your own risk :-).  Strongly encourage you using the tested and supported code releases :-).

I believe you are reporting a couple of items on this ticket:
- AWS best practice actually mandates that we use tightly scoped and unique roles for every purpose, hence the multitude of roles which exist in each AWS account.  This is actually a good thing, as it means the scope of any potential vulnerability would be limited and prevent lateral movement;
- The deployed roles are used by both the Accelerator state machine on each execution, by enabled AWS services in the account(s) including config rules and SSM remediation documents, we do not believe it would make sense to cleanup the roles;
- I would agree with you, the quantity of cdk roles is not ideal, but also not a problem.  The new AWS CDK installer deploys 4 roles per region and their is nothing we can easily do about this.  What we did do when we moved from the legacy installer (in `v1.2.6-a`) to the new installer in the `main` branch was centralize all the CDK buckets and roles in a single central account.  Had we not done this you would have had those 68 roles in every account, instead they only exist in the central-operation-services account.  The role names are also largely controlled by CDK;
- I accepted your other bug report and we will research the failure to cleanup 'anything' when we stop 'managing' a region.  In the meantime, you can manual remove any stacks in reverse order, from the regions you wanted un-managed regions (Phase5, then Phase 4, ...) and this should cleanup the extra roles for the regions for which you do not want to secure

Hopefully this helps clarify!

**Comment by rverma-nsl** [comment]
Hi Brian,

Just a note on this, even if you look at control tower implementation, they also have a single role for managing control tower operations. The whole process can be justified if you consider ASEA as a single entity. 

Infact if we are using tightly scoped role the whole proposal got invalidated. It actually come from the observation that we are having multitude of roles having AdministratorAccess, I would rather have 1 or 2 Roles having admin Access, few with poweruseraccess and unlimited with scoped access. I am afraid of if an auditor deploy something like https://github.com/salesforce/policy_sentry and identified that we have so many over-provisioned roles.

**Comment by Brian969** [comment]
Hi,

Unfortunately, your suggestion violates our security practices (and is therefore not something we will consider).  It is important to note that the roles you keep referencing are only usable by the CloudFormation Service, all the other tightly scoped roles are used by other services like custom resource Lambda's - considerably different use cases.

As previously stated, I cannot change the way those CDK* roles work/are created/deployed as this is the way the CDK was designed and functions.  If you have an enhancement suggestion for the CDK team, I'm going to suggest you pursue your enhancement requests directly with [them](https://github.com/aws/aws-cdk).  If they decide to change the behavior, please let us know so we can incorporate when available. 

Sorry, we couldn't be of more help.
