### ISSUE TITLE
[ENHANCEMENTS] Various Fit Finish enhancements

### ISSUE THREAD

**Issue by Brian969** [aws-samples/aws-secure-environment-accelerator#668]
**Required Basic Info**
- Accelerator Version:  v1.3.1

**Describe enhancements**
1. SSM document sharing API call not paginated
    - deploying new SSM documents to customers with over 20 accounts fails.
1. Enable 'deletion protection' on all ASEA deployed ALB and NLB's
    - also ensure we can still remove them if customer removes from config file (i.e. does not cause SM failure)
2.  Some log groups missing retention settings and subscriptions
    - example Ops account (4 of 32) missing settings:
    - /aws/lambda/ASEA-Operations-Phase5-CustomCentralLoggingSubscri-W8YILGMA7ROF
    - /aws/lambda/ASEA-Operations-Phase5-CustomS3PutBucketReplicatio-1CJZTP9WIDR2C
    - /aws/lambda/ASEA-Operations-Phase5-CustomS3PutBucketVersioning-16N94KMJSEBQO
    - /aws/lambda/ASEA-Operations-Phase5-CustomSSMIncreaseThroughput-I0QB3BI8PBG0
3. rsyslog NLB missing central logging
4. add an HTTPS policy to all ASEA deployed buckets including cdk buckets
    - test to make sure it doesn't break anything
```json
    {
      "Action": "s3:*",
      "Effect": "Deny",
      "Resource": [
        "arn:aws:s3:::DOC-EXAMPLE-BUCKET",
        "arn:aws:s3:::DOC-EXAMPLE-BUCKET/*"
      ],
      "Condition": { "Bool": { "aws:SecureTransport": "false" } },
      "Principal": "*"
    }
```
6. Apply back-off retry fixes:
    - backport Gilles Gitlab backoff-retry fix: in \src\lib\common\src\aws\backoff.ts
       - ("fix(core): Add additional retry exception type for AWS Organizations")
    - also see email from Brian with another potential fix in Phase 4 Error: Associating Hosted Zones
       - specifically, add backoff-retry on "ConcurrentModifications" === e.code`
       - while use the email as general guidance, fix properly in the base codebase :-).

6. A customer indicated we applied the "Quarantine-New-Object" SCP to accounts in the UnManaged OU.  Can you make sure we 100% leave the UnManaged OU alone ---> ***Unable to reproduce***

**Comment by naveenkoppula** [comment]
1. Enable 'deletion protection' on all ASEA deployed ALB and NLB's
	- Created a custom resource depends on ALB and enables Deletion protection also disable deletion 		 
   protection on Delete ALB
3. rsyslog NLB missing central logging
	- Enabling Access Logging after creation irrespective of Configuration
