### ISSUE TITLE
[FEATURE] Consider integrating with STNO

### ISSUE THREAD

**Issue by rverma-nsl** [aws-samples/aws-secure-environment-accelerator#681]
Serverless transit-network-orchestrator (STNO) is higher level of automation supported in automatic subnet addition to transit gateway route table. 

More details https://aws.amazon.com/solutions/implementations/serverless-transit-network-orchestrator/
Github: https://github.com/awslabs/serverless-transit-network-orchestrator

We can either migrate to that, or vice-versa, add the automations to this repo. Important one is the web interface which is created to help control, audit, and approve (transit) network changes.

**Comment by rverma-nsl** [comment]
One more pre-requisite for this is to add the capability of attaching tags to subnet, Current `SubnetDefinitionConfig` lacking this.

**Comment by Brian969** [comment]
We already perform many of those capabilities and plan to enhance via: https://github.com/aws-samples/aws-secure-environment-accelerator/issues/494 design spec.  Tags: what is your ask?  A customer could provide a key:value pair in the subnet\definition and have it applied to a subnet?

**Comment by rverma-nsl** [comment]
Actually that is not the main requirement but having an approval workflow (not so technical) is much preferred.

**Comment by Brian969** [comment]
- It is understated but the approvals process is part of "step 8", which is not yet fully refined.
- the vpc-template, which is marked as opt-in, would have an approval-required: true/false flag.
- if true, when the Service Catalog item was executed, it would not result in a VPC creation until someone from the cloud team approved/took action...
- would this meet your requirement?

**Comment by rverma-nsl** [comment]
yes, this would be very helpful
