### ISSUE TITLE
[FEATURE] Consider adding account alias

### ISSUE THREAD

**Issue by rverma-nsl** [aws-samples/aws-secure-environment-accelerator#683]
Account aliases helps a lot while doing switch iam by referencing by account name in place of account id.

**Comment by Brian969** [comment]
We've been pushing the use of AWS SSO which displays account name and allows for federation to many different identity providers (MAD, ADC, Ping, Octa, AzureAD, etc.) and automates the provisioning of roles in accounts.  Centralized identity is critical for most security regimes.  Any reason you don't use AWS SSO (no cost service)?  Definitely a good suggestion for those logging in via the console interface.

**Comment by rverma-nsl** [comment]
Yes we are using aws sso, the only exception is assuming PBMM-pipelineRole which we are assuming a lot while working with accelerator :)

**Comment by Brian969** [comment]
While this sounds easy, this is actually a hard problem to solve:
- AWS account names do not need to be unique (only account # and email address are guaranteed unique)
- AWS account aliases MUST be unique across all AWS customers
- any customer can pick any alias, blocking its use by all other customers
- to solve this within a customer we create the account KEY by appending a random hash to the account name in the config file
- to solve this in other areas we append a random hash to bucket names, etc.
- In this case, appending a random hash defeats the point of setting an alias
- I see no reliably way to guarantee we can successfully set an account alias and see it causing more frustration than value as customers may need to attempt multiple values before being successful

Based on this and many higher priority feature requests, closing this enhancement request
