### ISSUE TITLE
[BUG][Functional] Lack of validation for default-cwl-retention leads to Never expire for CloudWatch Logs

### ISSUE THREAD

**Issue by rjjaegeraws** [aws-samples/aws-secure-environment-accelerator#692]
Bug reports which fail to provide the required information will be closed without action.

**Required Basic Info**
- Accelerator Version: v1.3.1
- Install Type: Upgrade
- Upgrade from version: v1.2.2

**Describe the bug**
If the config file, the setting for "default-cwl-retention" allows a number, but the StateMachine does not validate the input. Entering an incorrect value will fail the PutRetention action that the supporting lambda function attempts to execute.

**Failure Info**
- What error messages have you identified, if any: 
- Invalid retention value. Valid values are: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
- What symptoms have you identified, if any: CloudWatch Logs show "Never expire" 

**Required files**
- Please provide a copy of your config.json file (sanitize if required)

**Steps To Reproduce**
1. In the config file, change the value for "default-cwl-retention" to the number 55
2. Run the StateMachine
3. Create a new Log Group
4. Validate that a subscription is applied (ie, the Lambda fired)

**Expected behavior**
The State Machine fails during the validation phase with an error message stating that the value for "default-cwl-retention" is not valid.

**Comment by Brian969** [comment]
This behaviour is documented here in bullet 2: https://github.com/aws-samples/aws-secure-environment-accelerator/blob/main/docs/installation/customization-index.md#13-other-configuration-file-hints-and-tips.  As we work on a config file GUI, we could look at adding this check to the GUI validation.
