### ISSUE TITLE
[FEATURE] Support cloudwatch cross account-cross regions

### ISSUE THREAD

**Issue by rverma-nsl** [aws-samples/aws-secure-environment-accelerator#693]
**Required Basic Info**
- Accelerator Version:  1.30.2

**Is your feature request related to a problem? Please describe.**
While the operations account suppose to be center for operations, the lack of central monitoring is a big hurdle in the architecture. Aws support out of box this feature.
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Cross-Account-Cross-Region.html#cross-account-and-AWS-organizations

**Describe the solution you'd like**
Implement cloudwatch permissions by default

**Comment by Brian969** [comment]
We already do this :-).  This is set by global-options\central-operations-services\cwl: true, followed by the value cwl-access-level: "full", for example.  You can also allow for the security account by setting cwl: true for access from that account as well (you can only specify cwl-access-level in one of the two locations).  Then, in the post install instructions follow step 1v, as their is no API to turn on the multi-account selector drop-down.  Hope this helps!
