### ISSUE TITLE
[ENHANCEMENT] Create public hosted zone without VPC

### ISSUE THREAD

**Issue by rverma-dev** [aws-samples/aws-secure-environment-accelerator#702]
**Required Basic Info**
- Accelerator Version:  (eg. v1.3.x)

**Describe the solution you'd like**
Since ASEA can request certificates from acm in deploy 1, it would be nice if we can also create public hosted zones outside vpc in deploy 0 state

**Comment by Brian969** [comment]
I knew someone would catch me on this.  We had it outside VPC and moved to VPC for consistency with private zones when we enabled creating private zones in any account, broke my rule of never limiting platform capabilities...

**Comment by rverma-nsl** [comment]
so there is no workaround for this currently, we have to have a vpc for creating a hosted zone. I hope we revert this condition soon.

**Comment by archikierstead** [comment]
ASEA not working on new features see README.
