### ISSUE TITLE
[BUG][Functional] Unable to assume role created by the SEA

### ISSUE THREAD

**Issue by rjjaegeraws** [aws-samples/aws-secure-environment-accelerator#713]
Bug reports which fail to provide the required information will be closed without action.

**Required Basic Info**
- Accelerator Version:  v1.3.1
- Install Type: Upgrade
- Upgrade from version: v1.2.5

**Describe the bug**
After using the SEA to create a role in an OU workload AWS Account, it cannot be used. Any attempt to assume the role will fail. The cause is the SEA applies a tag to the created role, and this SCP guardrail prevents the role from being assumed:
```
{
      "Sid": "Tag2",
      "Effect": "Deny",
      "NotAction": [
        "iam:PassRole",
        "iam:GetRole",
        "iam:GetRolePolicy",
        "iam:ListAttachedRolePolicies",
        "iam:ListInstanceProfilesForRole",
        "iam:ListRolePolicies",
        "iam:ListRoles",
        "iam:GetInstanceProfile",
        "iam:GetLoginProfile",
        "iam:ListInstanceProfiles"
      ],
      "Resource": "*",
      "Condition": {
        "StringEquals": {
          "iam:ResourceTag/Accelerator": "${ACCELERATOR_NAME}"
        },
        "ArnNotLike": {
          "aws:PrincipalARN": ["arn:aws:iam::*:role/${ORG_ADMIN_ROLE}", "arn:aws:iam::*:role/${ACCELERATOR_PREFIX}*"]
        }
      }
    },
```

**Failure Info**
- What error messages have you identified, if any: 
An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::xxxxxxxxxx:assumed-role/TempAdmin/zzzzzzzz is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::bbbbbbbbbb:role/Demo-Role

**Steps To Reproduce**
1. Login to the "Operations" account
2. Create a role called "TempAdmin" and assign it AdministratorAccess permissions
3. Apply the following role to the 'Dev' OU 'roles' configuration.
```
{
            "role": "Demo-Role",
            "type": "other",
            "policies": ["AdministratorAccess"],
            "boundary-policy": "Default-Boundary-Policy",
            "source-account": "operations",
            "source-account-role": "TempAdmin",
            "trust-policy": "none"
}
```
4. Ensure that you have a workload account within the "Dev" OU. If not, create one.
5. Commit the config.json file
6. Run the statemachine
7.  Confirm that the "Demo-Role" exists in an account in the DEV ou
8. While using the Operations "TempAdmin" role, attempt to assume role to "Demo-Role"

**Expected behavior**

When assuming the "Demo-Role" from within the "Operations" account, a successful role chain to an account in the "Dev" OU can be completed by assuming the "Demo-Role". 

It is blocked because of the Tags assigned to the role.

**Comment by Brian969** [comment]
Will be fixed in v1.3.3
