### ISSUE TITLE
[BUG] [SM] New Perimeter ALBs cannot be created

### ISSUE THREAD

**Issue by dugas-sourced** [aws-samples/aws-secure-environment-accelerator#726]
**Required Basic Info**
- Accelerator Version: v1.3.2
- Install Type: Upgrade
- Upgrade from version: v1.2.4
- Which State did the Main State Machine Fail in: Phase 3 (CloudFormation Stack: *PBMMAccel-Perimeter-Phase3*)

**Describe the bug**
If the configuration defines _new_ ALBs in the Perimeter account, Phase3 fails because a custom resource (CR) is invoked to apply deletion protection to the ALB(s) and the CR fails to retrieve the ALB despite having a legitimate ALB ID. (Race condition indicator.)

**Failure Info**
- One instance of the specific error message from CloudWatch Logs:
```
    "errorCode": "LoadBalancerNotFoundException",
    "errorMessage": "Load balancer 'arn:aws:elasticloadbalancing:ca-central-1:<account_id_redacted>:loadbalancer/app/Public-DevTest-perimeter-alb/5fc3bd37f7f4c6e7' not found",
```
- The error was readily repeatable. We had to eliminate the new ALBs from the configuration in order to continue & complete the upgrade. (They were not absolutely necessary for our environment.)

**Required files**
Please find attached:
* The CloudFormation template we captured while the corresponding CloudFormation Stack was undergoing update and before stack failure.
* A CloudTrail event capturing a representative instance of the error.

[phase3-error-cloudformation.template.json.txt](https://github.com/aws-samples/aws-secure-environment-accelerator/files/6416268/phase3-error-cloudformation.template.json.txt)
[phase3-error-cloudwatch.log.json.txt](https://github.com/aws-samples/aws-secure-environment-accelerator/files/6416269/phase3-error-cloudwatch.log.json.txt)

**Steps To Reproduce**
1. Add a new ALB to the Perimeter ALBs array (and add a corresponding security group to the local Perimeter VPC, or re-use an existing one).
2. Re-run the state machine
3. See error in Phase 3's CloudFormation stack in the Perimeter account

**Expected behavior**
The expectation is that the ALBs were deployed with deletion protection successfully applied by the Lambda Custom Resource, allowing Phase3 to pass.

**Screenshots**
N/A

**Additional context**
The SEA calls its own Lambda custom resource to enable deletion protection on the Perimeter ALBs. The Lambda code fails because the Application Load Balancer can't be retrieved by its ID.

Given the ALB ID is passed to the Lambda, this is probably a race condition in which a Resource ID has been generated but the full resource is not yet retrievable. One possible solution would be to ensure the Custom Resource includes the ALB logical ID in its "DependsOn" array, to ensure the resource is available for modification.

**Comment by Brian969** [comment]
Hi - Can you clarify - "**new** ALBs" and "We had to eliminate the **new** ALBs from the configuration in order to **continue & complete the upgrade**." - do I understand you were BOTH attempting to upgrade AND attempting to add an ALB at the same time?
- Changing the config (other than required changes) during an upgrade is highly discouraged :-)
- We've run numerous tests adding alb's and have not been able to reproduce the problem - is this only a problem during upgrade's with **new** alb's?

**Comment by dugas-sourced** [comment]
Clarifications:

1. These were *new* ALBs in the Perimeter account being added at the same time as the upgrade's first execution of the state machine.
2. That ^^ was NOT done on purpose - at some point we had changed the key to "xxalb" to by-pass their creation and I errantly fixed the key, mistakenly instating them. 100% agree that upgrading and modifying at the same time is BAD.

With regards to: "is this only a problem during upgrade's with new alb's?"

Now that the state machine has run completely and successfully (multiple times!) since the upgrade process, we'll add the ALB configuration to the Perimeter account to verify that they can be deployed were they actually needed. Provided that works, we'll  close this issue.

**Comment by dugas-sourced** [comment]
In the interest of closure, and because we're not going to be deploying external ALBs via the SEA in the immediate future, I'm closing this and thanking the participants for their time. Cheers!
