### ISSUE TITLE
[FEATURE] Support github along with codecommit

### ISSUE THREAD

**Issue by rverma-nsl** [aws-samples/aws-secure-environment-accelerator#746]
Since codebuild already support github, it would be very helpful to support github too. It would really simplify the auditing needs of an organization.

**Comment by Brian969** [comment]
Hi, You mean add support to allow deploying new versions from CodeCommit (will actually be supported in v1.5), or add support to allow storing the config.json (and sub-files) in GitHub?  
- At this moment I am not in support of the 2nd option.  It adds too many external dependencies, including networking issues which could cause issues and add complexity.  We also have other higher priority enhancements which I believe could bring more value to customers at this time.  Just my initial thoughts, not ruling it out...

**Comment by rverma-nsl** [comment]
What proposed is allow storing config.json in Github.

I agree that this is not a priority it, but you have acknowledge that the userbases who are using Github+AWS is way more than Code commit + AWS. It is very weird to manage two level of access controls. Then the  PR based workflow is missing for new route/vpc addition. 

We are even managing replicated security groups like (onprem access), iam roles and policies through this. So as this is growing PR would become more essential.

You can easily de priortized this :)

**Comment by rverma-nsl** [comment]
Anyways we are eagerly awaiting for 1.5, is there any timeline in your team is targeting :)

**Comment by Brian969** [comment]
> Anyways we are eagerly awaiting for 1.5, is there any timeline your team is targeting :)

"Hoping" to be code complete this week, lots of changes - so need to work through some fairly vigorous testing, security reviews and publishing process.  Hoping the first half of July, but depends on what challenges we encounter, I want to ensure we release a stable product.

**Comment by Brian969** [comment]
> What proposed is allow storing config.json in Github.
> 
> I agree that this is not a priority it, but you have acknowledge that the userbases who are using Github+AWS is way more than Code commit + AWS. It is very weird to manage two level of access controls. Then the PR based workflow is missing for new route/vpc addition.
> 
> We are even managing replicated security groups like (onprem access), iam roles and policies through this. So as this is growing PR would become more essential.
> 
> You can easily de priortized this :)

Makes sense.  Maybe once we have the new release with all the updated dependencies, etc. this is something you or your team could contribute?

**Comment by Brian969** [comment]
As this moves away from native AWS services (a core project objective) and adds complexity and dependencies on 3rd party tooling on a core solution component, this is not a planned enhancement at this time.
