### ISSUE TITLE
[FEATURE] Add script for development mode to generate config.json from split yaml

### ISSUE THREAD

**Issue by rverma-nsl** [aws-samples/aws-secure-environment-accelerator#748]
The capability of breaking a large config.json into smaller chucks is awesome.

However while doing local cdk operations i.f from cdk.sh/(ts), it only expects input in form of config.json.
It would be super nice to be able to generate config.json for local run from the original yaml files, or even better in place of config.json, provide the path of config.yaml and it work out of box.

The first option could be little simple since we probably have the same support in pipeline run. Need to figure out how to integrated the same in cdk.ts.

Second option is little trickier, but could be more developer friendly since now we can avoid copy paste.

**Comment by Brian969** [comment]
Understood - let me chat with the team on this.  Sounds like we need to do a better job on some of the developer guidance/optimization.

**Comment by Brian969** [comment]
See see PR#753 as an enhancement in this area.  As we accept multi-part config files, but always internally utilize a single config file, this is not a planned enhancement.
