### ISSUE TITLE
[BUG] [SM]  PBMMAccel-CreateAccountEventTrigger_sm failes when user is not Federated

### ISSUE THREAD

**Issue by jblaplace** [aws-samples/aws-secure-environment-accelerator#749]
**Required Basic Info**
- Accelerator Version:  1.2.2
- Install Type: Clean
- Upgrade from version: (N/A or v1.x.y)
- Which State did the Main State Machine Fail in: N/A

**Describe the bug**
We created an account using Terraform. The Terraform provider was using a IAM User credentials.
The user was not Federated.

CreateAccountEventTrigger_sm  failed with Invalid path '$.detail.userIdentity.sessionContext.sessionIssuer.userName': The choice state's condition path references an invalid value."

When looking at the input payload for the SM; indeed there is no sessionContext. But as per the IAM doc it is expected NOT to have a sessionContext when not being Federated and that field is optional.

**Failure Info**
- What error messages have you identified, if any:  failed with Invalid path '$.detail.userIdentity.sessionContext.sessionIssuer.userName': The choice state's condition path references an invalid value."
- What symptoms have you identified, if any:

**Required files**
- Please provide a copy of your config.json file (sanitize if required)
- If a CodeBuild step failed- please provide the full CodeBuild Log
- If a Lambda step failed - please provide the full Lambda CloudWatch Log
- In many cases it would be helpful if you went into the failed sub-account and region, CloudFormation, and provided a screenshot of the Events section of the failed, deleted, or rolled back stack including the last successful item, including the first couple of error messages (bottom up)

**Steps To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Brian969** [comment]
- This was fixed in v1.2.5 - https://github.com/aws-samples/aws-secure-environment-accelerator/releases/tag/v1.2.5
- Also: All customers were supposed to upgrade to v1.2.5+ before March 31st, 2021 as AWS deprecated some underlying API's we were dependent upon - not sure of the impact...
