### ISSUE TITLE
[FEATURE] Minimum cost MVP including perimeter account for personal/contractor shadow PBMM environment

### ISSUE THREAD

**Issue by obriensystems** [aws-samples/aws-secure-environment-accelerator#755]
**Required Basic Info**
To properly assess the enhancement request, we require information on the version of the Accelerator you based this request upon:
- Accelerator Version:  (eg. v1.1.6)
Latest

**Is your feature request related to a problem? Please describe.**
No 

**Describe the solution you'd like**

this is more of a documentation verify during a minimally viable SEA install on a clean account that includes the perimeter account.  Once I have the system up i will iterate down to the minimum cost MVP
Initially documenting on http://wiki.obrienlabs.cloud/display/DEV/AWS+Secure+Environment+Accelerator 
I will port or mirror the details as I go to the wiki/readme here

**Describe alternatives you've considered**

**Additional context**

Be warned - I approach this piece of work as an overly enthusiastic but humble developer - or at least I am tentatively hopeful that I can complete the install.

**Comment by Brian969** [comment]
Hey!
- did you take a look at option #5, which was add last month: https://github.com/aws-samples/aws-secure-environment-accelerator/blob/main/docs/installation/customization-index.md - this is a start in this direction? :-).
- also, it is difficult to iterate down, easier to iterate up - some object types cannot be downsized (i.e. MAD), other objects cannot be easily removed (regions, VPC's, accounts), etc.
- "The question is can I combine the 2 accounts via AWS Organizations?" - Which 2 accounts?  Please keep in mind AWS accounts generally cost nothing, the resources you run in accounts that cost $.  Minimum deploy is 3 accounts per the ultra-lite example.

**Comment by obriensystems** [comment]
sounds good, I cleaned one of my accounts and will enable AWS organizations there - I asked to upgrade the limit from 4 to 6 accounts there and just got the limit approved.  I'll start with the light option - I see you recently added ultra-light - very nice.  Ideally i'd use the minimum config that keeps the perimeter account above the ultra-light - but will MVP the ultra-light to start.  The core test cases we are implementing are around direct S3 PUTs and SDK REST calls around the S3 Transfer Manager SDK and VPC Gateways leveraged via the transit gateway for APIGW/DynamoDB traffic between separate app accounts

**Comment by Brian969** [comment]
With the launch of v1.5.0 and updating example #5 to leverage NFW instead of 3rd party firewalls, I believe this meets the original ask with respect to PBMM.  If you were not using MAD as your identity source, it could be further streamlined between example 5 and example 3.
