### ISSUE TITLE
[BUG][OTHER] Managed AD Password Policy not updating after state machine run in existing Landing Zone

### ISSUE THREAD

**Issue by SteveZerrSourced** [aws-samples/aws-secure-environment-accelerator#758]
**Required Basic Info**

- Accelerator Version:  1.3.2
- Install Type: Upgrade
- Upgrade from version: 1.2.4
- Which State did the Main State Machine Fail in: N/A

**Describe the bug**
Initial deployment of the Accelerator configures the Managed AD password policy with a maximum 90 day password age. We are attempting to change this configuration to 60 days.

For context, we have split config.json into units and converted to YAML. We have also implemented configuration changes to the landing zone and performed upgrades to the accelerator since splitting and converting to YAML. We can confirm that the state machine is successfully compiling the raw `config.json`.

We have updated the following section of the operations-prod.yaml to set the max-age to 60 days:

```yaml
password-policies:
      complexity: true
      failed-attempts: 6
      history: 24
      lockout-attempts-reset: 30
      lockout-duration: 30
      max-age: 90
      min-age: 1
      min-len: 14
      reversible: false

```

We have verified that the change is updated in the raw config.json that is utilized by the state machine, and also verified that the CloudFormation stack responsible for deploying the password policy (PBMMAccel-Operations-Phase5) contains the updated commend for the new password policy:

```json
"configurePasswordPolicy": {
            "commands": {
              "a-set-password-policy": {
                "command": "powershell.exe -ExecutionPolicy RemoteSigned C:\\cfn\\scripts\\Configure-password-policy.ps1 -DomainAdminUser admin -DomainAdminPassword ((Get-SECSecretValue -SecretId arn:aws:secretsmanager:ca-central-1:<accountNumber>:secret:PBMMAccel/operations/mad/password).SecretString) -ComplexityEnabled:$True -LockoutDuration 00:30:00 -LockoutObservationWindow 00:30:00 -LockoutThreshold 6 -MaxPasswordAge:60.00:00:00 -MinPasswordAge:1.00:00:00 -MinPasswordLength:12 -PasswordHistoryCount:24 -ReversibleEncryptionEnabled:$false",
                "waitAfterCompletion": "0"
              }
            }
          }
```

However, the Managed AD password policy does not appear to change within the environment.

```powershell
Get-ADFineGrainedPasswordPolicy -Identity "CustomerPSO-01" -Credential $credential


AppliesTo                   : {CN=Domain Users,CN=Users,DC=$domain,DC=local}
ComplexityEnabled           : True
DistinguishedName           : CN=CustomerPSO-01,CN=Password Settings Container,CN=System,DC=$domain,DC=local
LockoutDuration             : 00:30:00
LockoutObservationWindow    : 00:30:00
LockoutThreshold            : 6
MaxPasswordAge              : 90.00:00:00
MinPasswordAge              : 1.00:00:00
MinPasswordLength           : 12
Name                        : CustomerPSO-01
ObjectClass                 : msDS-PasswordSettings
ObjectGUID                  : c5f0c641-b787-4020-8643-84e41bfa734a
PasswordHistoryCount        : 24
Precedence                  : 10
ReversibleEncryptionEnabled : False
```

**Failure Info**

- What error messages have you identified, if any: No errors
- What symptoms have you identified, if any:
  - MaxPasswordAge policy in Managed AD does not update to new value.

**Required files**
[operations-prod-redacted.yaml.zip](https://github.com/aws-samples/aws-secure-environment-accelerator/files/6736383/operations-prod-redacted.zip)

**Steps To Reproduce**

1. Update `max-age` parameter of `password-policies` in Managed AD section of configuration
2. Commit changes to PBMMAccel-Config-Repo
3. Rerun state machine
4. Verify new parameters present in `PBMMAccel-Operations-Phase5`
5. SSM into `PBMMAccel-RDGW` ec2 instance and execute `Get-ADFineGrainedPasswordPolicy -Identity "CustomerPSO-01" -Credential $credential` to review Active Directory password policy

**Expected behavior**
Command `Get-ADFineGrainedPasswordPolicy -Identity "CustomerPSO-01" -Credential $credential` should return the following:

```powershell
Get-ADFineGrainedPasswordPolicy -Identity "CustomerPSO-01" -Credential $credential


AppliesTo                   : {CN=Domain Users,CN=Users,DC=$domain,DC=local}
ComplexityEnabled           : True
DistinguishedName           : CN=CustomerPSO-01,CN=Password Settings Container,CN=System,DC=$domain,DC=local
LockoutDuration             : 00:30:00
LockoutObservationWindow    : 00:30:00
LockoutThreshold            : 6
MaxPasswordAge              : 60.00:00:00
MinPasswordAge              : 1.00:00:00
MinPasswordLength           : 12
Name                        : CustomerPSO-01
ObjectClass                 : msDS-PasswordSettings
ObjectGUID                  : c5f0c641-b787-4020-8643-84e41bfa734a
PasswordHistoryCount        : 24
Precedence                  : 10
ReversibleEncryptionEnabled : False
```

Additionally, `Get-ADUserResultantPasswordPolicy` should return the updated password policy for any given domain user showing the updated password policy.

**Additional context**

It is noteworthy that [the following changes are documented as not being allowed](https://github.com/aws-samples/aws-secure-environment-accelerator/blob/main/docs/operations/operations-troubleshooting-guide.md#323-compare-configurations) when reruning the state machine to update the landing zone configuration:

- changing the ID, VPC, subnet, region, size, DNS, Netbios of a Managed Active Directory;
- disabling a Managed Active Directory;

If the change we are trying to make is also not supported, this documentation should be updated. We would also request that this type of change be supported.

We have also noted the following error logged in `cfn-init-cmd.log`:

```
2021-06-29 21:34:29,190 P1844 [INFO] ------------------------------------------------------------
2021-06-29 21:34:29,190 P1844 [INFO] Completed successfully.
2021-06-29 21:34:29,300 P1844 [INFO] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
2021-06-29 21:34:29,300 P1844 [INFO] Config join
2021-06-29 21:34:29,425 P1844 [INFO] ============================================================
2021-06-29 21:34:29,425 P1844 [INFO] Command a-join-domain
2021-06-29 21:34:47,364 P1844 [INFO] -----------------------Command Output-----------------------
2021-06-29 21:34:47,364 P1844 [INFO]    ValidationError: Stack arn:aws:cloudformation:ca-central-1:<account_id>:stack/PBMMAccel-Operations-Phase5/<redacted> is in UPDATE_COMPLETE state and cannot be signaled
2021-06-29 21:34:47,364 P1844 [INFO]    Command failure in Add-Computer C:\cfn\scripts\Join-Domain.ps1 on line 19
2021-06-29 21:34:47,364 P1844 [INFO]    Exception: System.InvalidOperationException: Cannot add computer
2021-06-29 21:34:47,364 P1844 [INFO]    EC2AMAZ-<redacted> to domain <redacted> because it is already in that domain.
2021-06-29 21:34:47,364 P1844 [INFO]    At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\AWSQuickStart\AWSQuickSta
2021-06-29 21:34:47,364 P1844 [INFO]    rt.psm1:314 char:13
2021-06-29 21:34:47,364 P1844 [INFO]    +             throw $CmdSafeErrorMessage
2021-06-29 21:34:47,364 P1844 [INFO]    +             ~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-06-29 21:34:47,364 P1844 [INFO]        + CategoryInfo          : OperationStopped: (Command failure...in that dom
2021-06-29 21:34:47,364 P1844 [INFO]       ain.:String) [], RuntimeException
2021-06-29 21:34:47,364 P1844 [INFO]        + FullyQualifiedErrorId : Command failure in Add-Computer C:\cfn\scripts\J
2021-06-29 21:34:47,364 P1844 [INFO]       oin-Domain.ps1 on line 19
2021-06-29 21:34:47,364 P1844 [INFO]        Exception: System.InvalidOperationException: Cannot add computer EC2AMAZ-8
2021-06-29 21:34:47,364 P1844 [INFO]       <redacted> to domain <redacted> because it is already in that domain.
2021-06-29 21:34:47,364 P1844 [INFO]
2021-06-29 21:34:47,364 P1844 [INFO] ------------------------------------------------------------
2021-06-29 21:34:47,364 P1844 [ERROR] Exited with error code 1
```

**Comment by Brian969** [comment]
Hi Steve,
Per [FAQ #1.1.8](https://github.com/aws-samples/aws-secure-environment-accelerator/blob/main/docs/faq/faq.md#118-i-deployed-aws-managed-active-directory-mad-as-part-of-my-deployment-how-do-i-manage-active-directory-domain-users-groups-and-domain-policies-after-deployment) - we only set the password policy during the initial deployment.  Subsequent updates need to completed [directly](https://docs.aws.amazon.com/directoryservice/latest/admin-guide/assignpasswordpolicies.html) using Microsoft Active Directory Administrative Center.

**Comment by SteveZerrSourced** [comment]
Hi Brian,

Thanks for the response. We'll update the policy manually.

We do agree that the Accelerator should not create/update/delete new AD users or groups, but hope that it will be taken into consideration that the Accelerator be able to update or align the domain password policy with the configuration, keeping a codified source of truth and preventing drift.
