### ISSUE TITLE
[BUG][Functional] SEA blocks CFN deletions by applying additional IAM policies

### ISSUE THREAD

**Issue by joshhodgson** [aws-samples/aws-secure-environment-accelerator#759]
Bug reports which fail to provide the required information will be closed without action.

**Required Basic Info**
- Accelerator Version:  v1.3.4
- Install Type: Clean
- Upgrade from version: N/A

**Describe the bug**
The SEA in its example configuration blocks CloudFormation from deleting IAM roles if not created with the required managed policies. This has been encountered when using [AWS Service Workbench](https://github.com/awslabs/service-workbench-on-aws), and it blocks SWB from being able to terminate workbenches as CloudFormation fails

**Failure Info**
The following 4 policies are added to the created IAM role
![image](https://user-images.githubusercontent.com/7606810/123981048-ed661700-d9b9-11eb-9238-0fd0034d858c.png)
And on CloudFormation stack delete the following error occurs
![image](https://user-images.githubusercontent.com/7606810/123981613-52ba0800-d9ba-11eb-8da1-9690ec173e3a.png)
 

**Required files**
- config.json as supplied in the sea example

**Steps To Reproduce**
1. Deploy a CFN template which creates an IAM role and Instance Profile assigned to an EC2 instance
2. Wait for the additional policies to be applied
3. Delete the CFN stack

**Expected behavior**
CloudFormation stacks should delete without 'manual intervention'

**Comment by Brian969** [comment]
Hi Josh,
The above error is not an SCP error and not something the ASEA is blocking.  The ASEA only blocks actions on IAM constructs (roles, policies, etc) created/controlled by the Accelerator (i.e. name starting with Accelerator prefix or tagged as such.  The above error states: "DETACH ALL POLICIES" before deleting the role - I believe this is your problem (CFN often does not understand order of operations and does not reverse the order on delete operations.)

**Comment by joshhodgson** [comment]
Hi Brian, thanks for coming back to me. Given CFN seems to only delete the policies it applies before deleting the role, would you have any recommendations for us to overcome this?

We can hard-code the AWS managed policies in our CFN templates going forward but given the example config has a customer-managed policy with (I believe) an arbitrary name, this means editing the template/requiring the user to enter it as a parameter on each launch, were we to deploy a CFN to a different ASEA environment. 

I feel like there might be a better way!

Thanks

**Comment by Brian969** [comment]
Can you share your CFN be helpful in testing your specific challenge.

**Comment by Brian969** [comment]
For historic reference:
- All instances without the appropriate IAM policies attached, we have a config rule that remediates and attaches them.  All instances must have these policies: "AmazonSSMManagedInstanceCore, AmazonSSMDirectoryServiceAccess, CloudWatchAgentServerPolicy", "${SEA::EC2InstaceProfilePermissions}".  The “EC2-Default-SSM-AD-Role” role can be used as a template.  The custom policy is also stored in parameter store (/ASEA/ident/policy/2/arn and /ASEA/ident/policy/2/name)
- To enable your stack to delete, you should create the role with these policies attached (during your CFN creation), so we don’t add these policies at a later time.  Then your CFN stack will properly remove the policies from the role during the role deletion (and not fail).
