### ISSUE TITLE
[FEATURE] Share the vpc parameters in parameter store when account sharing

### ISSUE THREAD

**Issue by rverma-nsl** [aws-samples/aws-secure-environment-accelerator#770]
When we share vpc subnets through ram, it would be very helpful if we can replicate the required parameters in the target accounts' parameter store too.

**Comment by Brian969** [comment]
Hey Rohit,
When you say "we share vpc subnets through ram", you mean the ASEA, right?  We do actually store those objects parameters in parameter store in the target account already.

**Comment by rverma-nsl** [comment]
I meant ASEA only, But i am not able to see any network related values in parameter store. I can values like
`/prefix/encrypt/acm/1/arn` or `/prefix/ident/policy/1/name`, but not something related to vpc or security group. These only exists in shared network account and not in target account.

Am i missing something?

**Comment by Brian969** [comment]
They should also be created in every 'shared' account - here is a screenshot from one of one of my developer accounts installed clean using the 133 release:
![image](https://user-images.githubusercontent.com/56414362/127503316-5afb47bf-47b9-482d-9fea-9a60256a49f2.png)
i.e.  I believe something is wrong with your specific deployment.
