### ISSUE TITLE
[BUG][Functional] Store Outputs to SSM fails when there are ~ 100 AWS Accounts in the Organization

### ISSUE THREAD

**Issue by rjjaegeraws** [aws-samples/aws-secure-environment-accelerator#782]
Bug reports which fail to provide the required information will be closed without action.

**Required Basic Info**
- Accelerator Version:  v1.3.4
- Install Type: Clean
- Upgrade from version: N/A 

**Describe the bug**
The Main State Machine's final 'Store Outputs to SSM' task fails when there are many AWS Accounts in the Organization.

**Failure Info**
- What error messages have you identified, if any:  Unable to find relevant error messages.
- What symptoms have you identified, if any: DynamoDB Metrics shows Throttled requests and consumed capacity units far above the provisioned amount.

**Required files**
- Please provide a copy of your config.json file (sanitize if required)

**Steps To Reproduce**
1. Have 97 AWS Accounts in the Organization
2. Create a new AWS Account and monitor the State Machine

**Expected behavior**
The SM completes without error

**Screenshots**
![image](https://user-images.githubusercontent.com/41204211/129620439-bb7a6e54-49a6-4624-9972-e8cd56b65c50.png)

**Additional context**
Switching the table capacity to OnDemand resolved this issue.

**Comment by Brian969** [comment]
Will be included in next minor release - merged with main.
