### ISSUE TITLE
[FEATURE] Support substituting Accelerator values into existing Fortinet FW config to bootstrap FWs

### ISSUE THREAD

**Issue by archikierstead** [aws-samples/aws-secure-environment-accelerator#784]
**Required Basic Info**
To properly assess the enhancement request, we require information on the version of the Accelerator you based this request upon:
- Accelerator Version:  1.3.6

**Is your feature request related to a problem? Please describe.**
Customer would like an automated FW re-deployment for DR purposes.  Firewalls  would be bootstrapped with custom FW config that ASEA has updated new values within if ASEA is re-deployed.

**Describe the solution you'd like**
Customer would like to use an existing FW config.  The config encapsulates a complex custom FW setup.  They would prefer not to have to diff changes in the event of a DR.  They would like to have a mechanism for ASEA to perform substitutions inside an existing FW config (dumped from FW) of new values from an Accelerator re-deployment.  This document subjected to aforementioned substitutions would be used to bootstrap the FWs.

https://github.com/aws-samples/aws-secure-environment-accelerator/blob/c3ed6e05a0f2c159455d7a303245ee11120abc15/reference-artifacts/SAMPLE_CONFIGS/firewall_file_available_variables.md 

**Describe alternatives you've considered**
Diff explained and considered.  Customer prefers an automated solution.

**Additional context**

**Comment by cauger-git** [comment]
Thank you James for creating the issue.

Yes, this is a feature we think would make a lot of sense in a disaster recovery scenario; being able to run the Accelerator using a firewall configuration backup that contains all our customizations (i.e. customized interfaces, tunnels, policies, etc.) and therefore have a fully configured/functional firewall once the Accelerator completes. 

As described by James, what we though could potentially work would be to use our most recent firewall configuration backup and patch the actual IP addresses with the variables that are expected by the Accelerator. These variables would then be replaced with the new values that resulted for the Accelerator network deployment, as it is currently the case when running the Accelerator with the basic firewall configuration.

We do not know if this actually requires any modifications on the Accelerator side as it already performs this variable to value replacement during deployment. Or in other words, if the Accelerator performs a pure search and replace for the variables, it could perhaps already support this. But our full firewall configuration backups currently have about 5K lines and perhaps we could be placing some of the variables here they are not expected or are ignored. Or perhaps there are some additional sections in our firewall backups that would not be expected by the Accelerator and cause other issues.

We may be experimenting with this in the near future; looking if we can automate the task of replacing actual values in a full configuration backup with the variables that are expected by the Accelerator and feed that as an input in a full Accelerator run. 

So please let us know if there is movement on this request or if you can think of reasons this has no chance of working. And we will also post any additional observations or suggestions we may have here.

Thank you,
Charles Auger
charles.auger@ised-isde.gc.ca

**Comment by archikierstead** [comment]
For others reference: One way you could potentially do this is to use Cloudwatch event scheduler kick off a Lambda say once a day to SSH to the Fortigates, dump the FW config to an s3 bucket that will trigger a second Lambda to regexp it to insert the variables then place it in the ASEA s3 config bucket.  That way if you were to re-deploy ASEA it would use a current FW config.

**Comment by Brian969** [comment]
Hi,
I believe this is a request for Fortinet.  Unfortunately, Fortinet does not allow one to load a Fortinet backup file using the Fortinet bootstrap process which leverages AWS userdata (a Fortigate thing, not an AWS thing).  AWS is simply feeding a Fortinet Fortigate config file into Fortinet's bootstrap process (and these are just the exact commands in the exact order you'd need to type them if you entered them on the Fortigate command line).  (i.e. one challenge - you need to have the same Fortigate 'sections' multiple times, as you may not have everything defined before you get to the first occurrence of a section - I don't think the restore load process works this way and allows everything in a single section as it validates the entire config file at once, at the end.).

Yes - we perform a pure search/replace on ${VARIABLE} in the supplied "firewall.txt" config file.  They can be the auto-generate (dynamic) values described [here](https://github.com/aws-samples/aws-secure-environment-accelerator/blob/main/reference-artifacts/SAMPLE_CONFIGS/firewall_file_available_variables.md), or variables defined by you in the replacements section of the main accelerator config file.

Whatever file you provide, we will jam it into the firewall, after we replace any variables (if they exist) :-).  We have no control as to whether Fortinet accepts or rejects the file.  The current example was developed with extensive assistance and support from Fortinet, and is ultimately just a Fortigate config file.

Multiple options exist:
- take all your customizations and work them back into a new sample input file
  - this is easy if you backup the config immediately after a clean install, make all your changes, take another backup and use a text comparison tool to compare the two files.  Take the new items, and merge them into the appropriate spots of a new input config file (ignoring gui placement fields).  If you save that backup, you can use it to compare to the latest backup in a DR scenario, such that you can recover to latest backup.
- record the values of all your variables after deployment, in a DR scenario, reload with the sample config, record all the values and create a mapping table, search and replace the backup for each value from before and replace it with the new value, load the backup on top of the "oob sample deployment".
- I'm sure other options exist...

Unfortunately, this is all 3rd party and extremely vendor specific functionality that is outside the scope of work AWS is able to undertake.

**Comment by cauger-git** [comment]
Hi Brian, James,

Thank you for your assistance and understood that there is a fine line here between what AWS/Accelerator can do based on what is supported by Fortinet.

Brian, I’m not sure I understood all of what is in the first paragraph of your post. We started working with Fortigate when adopting the AWS SEA (have always used something else in the past) and are therefore still learning. But I think the bottom line is that in terms of using a configuration file, the Fortigate bootstrap process is different to it’s restore process; unlike the restore process, the bootstrap process cannot ingest a full configuration file backup. And therefore, the suggestion of feeding a full configuration file (even with the appropriate variables in place instead if actual IP addresses) during Accelerator deployment/Fortigate bootstrap is a no go. If you can please confirm.

We did perform a manual restore a few months ago. We had to do a clean run of the Accelerator and this was after a significant amount of changes had been made to the firewall configuration. As you suggested, we did a manual diff/merge of the fresh firewall configuration after the Accelerator completion and a backup taken previously. Although this worked, we did find it quite error prone, hence why we were looking for other options.

Charles

**Comment by Brian969** [comment]
Hi,

> "the Fortigate bootstrap process is different to it’s restore process; unlike the restore process, the bootstrap process cannot ingest a full configuration file backup."  {in the format output by the Fortigate backup process}
- Correct, this is my understanding.  But, it's not an AWS product, I defer to Fortinet and their experts.

> And therefore, the suggestion of feeding a full configuration file (even with the appropriate variables in place instead if actual IP addresses) during Accelerator deployment/Fortigate bootstrap is a no go. 
- you can craft / create a file that contains your entire firewall configuration, but, you cannot simply use the Fortigate backup file, it needs to be reconstructed.

I could be wrong, this is my experience/understanding.  James can connect you with someone at Fortinet who may be able to help you in this area.

BTW: I forgot to mention, if you do come up with something, we'd love if you contributed back.

**Comment by cauger-git** [comment]
Thank you Brian. We do have a contact at Fortinet and may probe that way now that I have a better understanding of the issues.

Yes, we’ll let you guys know if there are other developments on this. Please do the same, perhaps there are other government departments deploying Fortigate via the Accelerator that will look into making the disaster recovery scenario more “elegant”!
