### ISSUE TITLE
[FEATURE] Enhance structure of log archive bucket to support analytics

### ISSUE THREAD

**Issue by michaeldavie-amzn** [aws-samples/aws-secure-environment-accelerator#804]
**Required Basic Info**
- Accelerator Version: v1.3.8-a

**Is your feature request related to a problem? Please describe.**
Logs from different services are currently structured in different ways, making it difficult to work with them using data analysis tools such as Athena and OpenSearch.

**Describe the solution you'd like**
Implement the log archive structure recommended by the SIEM on Amazon OpenSearch Service project: https://github.com/aws-samples/siem-on-amazon-opensearch-service/blob/main/docs/configure_aws_service.md

**Describe alternatives you've considered**
I have adapted the Security Analytics Bootstrap project to support the current structure in Athena, and will attempt to do the same with the SIEM project.

**Additional context**
N/A

**Comment by rverma-nsl** [comment]
This is a good idea, by the way @michaeldavie-amzn did your forked the Security Analytics Bootstrap with your changes which currently works with ASEA pattern.

**Comment by Brian969** [comment]
- ASEA currently writes all CWL groups to a single folder, attached PR #861 (which includes PR #853 ) optionally breaks customer specified log streams into separate folders for easy ingestion by siem-on-amazon-opensearch-service project
- PR #853 deploys OpenSearch, and ingests the log files from the ASEA log-archive bucket leveraging the work from the https://github.com/aws-samples/siem-on-amazon-opensearch-service project

**Comment by drewdresser** [comment]
hi @michaeldavie-amzn - Is your log analytics package still a forked version of the Security Analytics Bootstrap or are we able to leverage that out of the box now? If forked, I'm interested in exploring what you have created specific for the SEA.

**Comment by michaeldavie-amzn** [comment]
@drewdresser Sorry for the delay in responding. I've switched roles and am not up to date on the latest developments. @Brian969, can you provide an update on the currently preferred approach for log analysis?
