### ISSUE TITLE
[BUG][DOCS] AWS Firewall

### ISSUE THREAD

**Issue by brianmingus2** [aws-samples/aws-secure-environment-accelerator#806]
The FAQ says we don't have to use Fortinet and can can use an AWS service. The documentation doesn't seem to cover this ideal use case. Is this actually supported at the present moment, and how do we do it? (Go without Fortinet, but still have a Firewall).

**Comment by Brian969** [comment]
This will be in the coming v1.5.x release, which we are doing everything to get out the door, ASAP (unfortunately, this release has taken us longer than expected to complete).  Per the project [board](https://github.com/aws-samples/aws-secure-environment-accelerator/projects/1), we are just finishing up the Control Tower integration and an upgrade script and have already started working through the internal release process.

**Comment by brianmingus2** [comment]
Thanks for the update. 

Control Tower, AWS Firewall, and a UI sounds great.

I wanted to comment that we may not always be able to install into the client root account, or we may need to gain the client's trust first by installing elsewhere, but without doing a full-blown migration to a new root account. It's also not clear how your idempotent stack will actually not interfere with whatever the client has going on if we do clobber their existing setup.

Thanks,

Brian

**Comment by Brian969** [comment]
- Unfortunately, we rely heavily on AWS Organizations, which requires we leverage a root / Organization Management account.  In these situations where you cannot leverage the root account, you will need to take a different approach/this solution is not a fit.  AWS has a strong focus on AWS organizations as a general best practice - so suggest working with your customers to move in this direction.
- FYI - we want to get the release out, so I am not sure what state the gui will be in - it will be alpha or beta and we will use it to get input as to the direction the UI will take in a future release from customers.
- For existing/brownfield customers, we actually recommend you NOT do a big-bang install - install with all the customers existing ou's listed in the "ignored-ous": ["UnManaged", "ignoreou-2", ignore-ou-3"] parameter.  These top level ou's will be unmanaged by the accelerator (except for items auto-activated by orgs like Guardduty and Macie).  Install only the mandatory asea accounts and the core ou (updating to 'Security' and 'Infrastructure' ou per latest aws multi-account guidance).  Once that looks good, add one top level ou at a time into governance to test the impact, starting with the customers lowest risk environments like sandbox, testing and working up through test, dev and prod.  (or start with a new organization and slowly migrate accounts and workloads over ass appropriate)
- Some typical impacts 
  - the only object we delete that is pre-existing is the default VPC's as it is AWS Best practice - we do not delete customer objects and we do not delete this VPC if it contains objects (we fail).  If a customer is using the default VPC, a flag can be specified to bypass this step on a per account or per region basis to allow for an install in this situation.
  - SCP's - these will prevent AWS API's, but won't destroy objects.  Should an SCP be negatively impactful to a workload, they can be fully customer modified (and set per ou).  the majority of our SCP's are scoped to Accelerator created objects plus additional security controls.  The v1.5 release will better separate  ASEA created protections from security SCP's like mandatory encryption, as modifying the ASEA protection SCP's could result in a broken ASEA.
  - we deploy new/additional prefixed objects - naming should be unique and not collide or clobber anything
  - the proposed architecture and security settings of many of the examples have some of the biggest impacts - centralized ingress/egress (lack of public subnets), the inability for the workload user to create VPCs and subnets and mandatory encryption at rest, but if that's not appropriate for your customer, can be easily adjusted to allow instead for unmanaged or mandaged spoke vpc's with IGW's.
  - we also have 3 config rules that include OOB remediation encrypting unencrypted s3 buckets and adding/updating instance profiles not configured for SSM - easily disabled if not appropriate
  -  best for you to test, but these are items that come to mind...
