### ISSUE TITLE
[BUG][Functional] Macie sensitive data findings not sent to Security Hub

### ISSUE THREAD

**Issue by michaeldavie-amzn** [aws-samples/aws-secure-environment-accelerator#811]
**Required Basic Info**
- Accelerator Version: v1.3.7
- Install Type: Clean
- Upgrade from version: N/A

**Describe the bug**
Macie is not configured to forward sensitive data findings to Security Hub.

**Failure Info**
- What error messages have you identified, if any: N/A
- What symptoms have you identified, if any: See screenshot

**Required files**
Default config

**Steps To Reproduce**
1. Go to Amazon Macie / Settings in any account
3. See that publishing of sensitive data findings is disabled

**Expected behavior**
Macie should be configured to forward sensitive data findings to Security Hub in all accounts.

**Screenshots**
![image](https://user-images.githubusercontent.com/89793678/134959016-15de481d-3a03-408c-a775-12c100e05d83.png)

**Additional context**
CLI workaround:
`aws macie2 put-findings-publication-configuration --security-hub-configuration publishClassificationFindings=true,publishPolicyFindings=true`

**Comment by Brian969** [comment]
- The addition of findings versus sensitive findings was a recent update to Macie
- The ability to publish sensitive findings has already been added to the coming v1.5.0 release
  -  see issue #752, item 6.
