### ISSUE TITLE
[FEATURE] Accelerator Wizard based GUI interface (to abstract/hide the configuration file) (Phase 2)

### ISSUE THREAD

**Issue by Brian969** [aws-samples/aws-secure-environment-accelerator#826]
Accelerator Wizard based GUI interface (to abstract/hide the configuration file)
- rough Alpha code is included in v1.5.0 to get preliminary customer feedback.
- drive the GUI to the next level

**Comment by Brian969** [comment]
- We released a very early GUI mock-up (attached to release artifacts)
  - also downloadable here: https://github.com/aws-samples/aws-secure-environment-accelerator/releases/download/v1.5.0/AWS-SEA-GUI-mockup-DoNotUse-v150-alpha.zip
- It is NOT ready for use with customer config files, even in test installations
- Test by unzipping, navigating to: src\ui\build, and opening index.html in a browser
- Requires utilization of a v1.5.0 config file (samples found in the reference-artifacts\SAMPLE_CONFIGS folder)
- We are only releasing to get feedback on the gui's direction

**Comment by archikierstead** [comment]
ASEA not working on new features see README.
