### ISSUE TITLE
[BUG][Functional] aws-controltower-ConfigRecorderRole is blocked by SCP

### ISSUE THREAD

**Issue by jblaplace** [aws-samples/aws-secure-environment-accelerator#871]
**Required Basic Info**
- Accelerator Version:  v1.5.0 + ControlTower
- Install Type: Clean
- Upgrade from version: N/A

**Describe the bug**
aws-controltower-ConfigRecorderRole is preventing for performing actions required generating hundreds of ASEA-AWS-Authorization-Failure alarms

**Failure Info**
- What error messages have you identified, if any: 
-"errorMessage": "User: arn:aws:sts::*:assumed-role/aws-controltower-ConfigRecorderRole/AWSConfig-Describe is not authorized to perform: cloudtrail:DescribeTrails with an explicit deny in a service control policy",  or "errorMessage": "User: arn:aws:sts::230863557407:assumed-role/aws-controltower-ConfigRecorderRole/configLambdaExecution is not authorized to perform: sagemaker:ListNotebookInstances with an explicit deny in a service control policy"
- What symptoms have you identified, if any:
Reception of hundreds of ASEA-AWS-Authorization-Failure alarms each day
**Required files**
- Please provide a copy of your config.json file (sanitize if required)

**Steps To Reproduce**
3. See error

**Expected behavior**
ControlTower config recorder should be able to perform its actions in all regions.
**Screenshots**

**Additional context**

**Comment by jblaplace** [comment]
The following tentative set of SCPs remediate the problem.
[scp.zip](https://github.com/aws-samples/aws-secure-environment-accelerator/files/7626917/scp.zip)

**Comment by Brian969** [comment]
Thanks JB - appreciate you working through the required tweaks - couple of questions:
- in sensitive - which APIs in OTHS needed the CT exception? (curious)
- in sensitive - why did you add CT to ACM and KMS (GBL2), I didn't think CT did anything with keys in sub-accounts (especially the non-home region)? (or were you keeping it consistent with the next policy?)
- in Part 0 - does CT really use the aws-controltower-* role to configure config (CON) and not the AWSControlTowerExecution role, or was this a pre-cautionary change?

Thank you!

FYI: Minor tweaks we will add:
- sensitive - remove duplicate lines 12 and 13
- Part-1 - add "arn:aws:iam::*:role/aws-controltower-*" to the Resource line of ROL
- unclass/sandbox - make PMP sections the same as the changes in sensitive
- prettier to repo format

**Comment by jblaplace** [comment]
I didn't do a deep dive to fine tune the SCPs. I simply looked where the AWSControlTowerExecution role was used and opted to follow suite. I agree that the SCPs I provided might grant unnecessary permissions.

**Comment by Brian969** [comment]
- Control Tower SCP fixes  added in PR#885
