### ISSUE TITLE
[BUG][Functional] Abnormal amount of AWS-Authorization-Failure ALARMS 

### ISSUE THREAD

**Issue by jblaplace** [aws-samples/aws-secure-environment-accelerator#875]
Bug reports which fail to provide the required information will be closed without action.

**Required Basic Info**
- Accelerator Version:  v1.5.0 with CT
- Install Type: Clean
- Upgrade from version: N/A

**Describe the bug**
AWS-Authorization-Failure ALARMS are generated because the way the CW ALARMS integrates with SNS is different in the Management account from the other accounts. In the management account the ALARMS action sends a notification to an 'in account' SNS Topic which has a Lambda subscriber. The Lambda relays the notification to the CENTRAL LOG Account. For the other accounts the cw alarms are configured to directly send notifications to the SNS Topics of the CENTRAL LOG Account. Because of this, we can see for each ALARM a warning that states: 'This action sends a message to an SNS topic in a different account. We're unable to verify whether the action is correctly configured.' The side effect is that SecurityHub running in those accounts generates Authorization Failure ALARMS because of this: (For each notification topic) AWSServiceRoleForSecurityHub/securityhub is not authorized to perform: SNS:ListSubscriptionsByTopic on resource: arn:aws:sns:ca-central-1:<snip>:ASEA-Notification-Ignore because no resource-based policy allows the SNS:ListSubscriptionsByTopic action

**Failure Info**
- What error messages have you identified, if any:  AWSServiceRoleForSecurityHub/securityhub is not authorized to perform: SNS:ListSubscriptionsByTopic on resource: arn:aws:sns:ca-central-1:<snip>:ASEA-Notification-Ignore because no resource-based policy allows the SNS:ListSubscriptionsByTopic action
- What symptoms have you identified, if any: Abnormal amount of AWS-Authorization-Failure ALARMS 

**Required files**
- Please provide a copy of your config.json file (sanitize if required)

**Steps To Reproduce**
1. Go to '...' Deploy the alarms in ALL accounts instead of just the management account.
3. See error

**Expected behavior**
Modify the resource policies of the notification topics in the LOG account to allow SNS:ListSubscriptionsByTopic or apply the same pattern as in the Management account.

**Screenshots**

**Additional context**
Add any other context about the problem here
[config.zip](https://github.com/aws-samples/aws-secure-environment-accelerator/files/7621036/config.zip)
.

**Comment by jblaplace** [comment]
The following resource policy on the topic(s) , adjusted per topic remediate the problem:
{
      "Sid": "5-Manual",
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": "sns:ListSubscriptionsByTopic",
      "Resource": "arn:aws:sns:ca-central-1:MY-ACCOUNT-ID:ASEA-Notification-High",
      "Condition": {
        "StringEquals": {
          "aws:PrincipalOrgID": "o-MY-ORGANISATION-ID"
        },
        "StringLike": {
          "aws:PrincipalArn": "arn:aws:iam::*:role/aws-service-role/securityhub.amazonaws.com/AWSServiceRoleForSecurityHub"
        }
      }
    }

**Comment by Brian969** [comment]
Validated: Add the above resource policy to the existing SNS resource policies on the 4 SNS topics in the log-archive account.  (Obviously updating the resource line and orgid line as required)

**Comment by rjjaegeraws** [comment]
@jblaplace , 
Could you clarify the Steps to Reproduce. Looking at your config file, I believe that the steps should say:
1. modify the config **alarms** section:
from the default:
```
"alarms": {
 "default-accounts": ["management"],
```
to the following:
```
 "alarms": {
        "default-accounts": [
          "ALL"
        ],
```

**Comment by jblaplace** [comment]
Correct alarms should be set to ALL and not just the management account, so that alarms are deployed in each workload account. Those alarms will try to send SNS using the topics in the log/archive account. That is why security hub will try to access those topics which don't allow sechub from other accounts.

I tried with explicit Principal to the role etc but none of that worked.
I could only get it to work using "*" as the Principal and working with Conditions to narrow down the scope of the caller to being SecHub within the Org.

**Comment by rjjaegeraws** [comment]
I've noticed that this issue is present in the CT baseline, but does not exist in the standalone baseline. I'm looking to compare why that is...

**Comment by Brian969** [comment]
yeah, because CT uses account instead of org trails, the CW Alarms also need to be deployed in every account.  SH does nothing in standalone for these rules as its an org trail (and in the org root we added an SNS topic).
