### ISSUE TITLE
Question: Log4j vulnerability for SEA

### ISSUE THREAD

**Issue by yoggsaronpuzzlebox** [aws-samples/aws-secure-environment-accelerator#889]
Hello,

I was wondering if there were any actions and or mitigation required  for the on going Log4j issue

[Log4j Issue](https://aws.amazon.com/blogs/security/using-aws-security-services-to-protect-against-detect-and-respond-to-the-log4j-vulnerability/)

**Comment by Brian969** [comment]
- The official AWS security guidance regarding Log4j can be found here: https://aws.amazon.com/security/security-bulletins/AWS-2021-006/ (in addition to the blog post you referenced)
- Security advisories specifically related to the ASEA are posted here: https://github.com/aws-samples/aws-secure-environment-accelerator/security/advisories
- As an open source project, customers can self-check the ASEA codebase for existence of log4j.  An example command to perform this search, which can be run in the root of your local ASEA code directory: `find . -type f | xargs -I{} grep -i log4j {} /dev/null`
  - It should be noted that the ASEA is written in Typescript, and not Java.

**Comment by yoggsaronpuzzlebox** [comment]
Thanks for This Brian
