### ISSUE TITLE
[BUG][OTHER] Rsyslog deployment doesn't work properly when using custom AMI that has CWA config present

### ISSUE THREAD

**Issue by para0056** [aws-samples/aws-secure-environment-accelerator#893]
Bug reports which fail to provide the required information will be closed without action.

**Required Basic Info**
- Accelerator Version: `v1.3.8a`
- Install Type: N/A
- Upgrade from version: N/A
- Which State did the Main State Machine Fail in: N/A

**Describe the bug**
(A clear and concise description of what the bug is.)

Rsyslog deployment does not work when using a custom AMI that has a CloudWatch agent configuration already present on the filesystem.

**Failure Info**
- What error messages have you identified, if any: N/A
- What symptoms have you identified, if any: N/A

**Required files**
Not a failure of the ASEA StateMachine / Lambda.

**Steps To Reproduce**
1. Modify the `rsyslog` deployment in the ASEA config.json to use an AMI that has a CloudWatch agent configuration file already defined in the filesystem.
2. Run the State Machine.
3.  The rsyslog ELB, ASG, and launch configuration will get created - but the EC2 instances won't come up healthy.
4. Upon inspecting the EC2 instance that's part of the rsyslog deployment, you'll notice that the CloudWatch Agent configuration file is malformed.
5. This is because the userdata that is injected by the Launch Configuration appends a basic CloudWatch Agent configuration to the CloudWatch Agent config.json file.
6. This is problematic if the base AMI that is used by the rsyslog deployment already contains a valid CloudWatch Agent config.json file, since the newly appended JSON (injected by the userdata) will render the CloudWatch Agent config.json invalid. In turn, the CloudWatch Agent will fail to start.

**Additional context**
A possible solution to this problem would be to modify the launch configuration userdata for the rsyslog deployment to do an overwrite of the CloudWatch Agent config.json file.

**Comment by rjjaegeraws** [comment]
Hi @para0056,

Could you provide the AWS region and value of `ssm-image-id` you used in your config file?

**Comment by para0056** [comment]
Thanks for your message @rjjaegeraws.
As it turns out, the AMIs we use are private so I'm not sure that providing you the image ID would do much good.
If it helps, the image is based on CentOS v7.
