### ISSUE TITLE
[BUG][Functional] protection for internal ELB's (not part of SCP and could be deleted )

### ISSUE THREAD

**Issue by OleksiyByegunov** [aws-samples/aws-secure-environment-accelerator#907]
**Required Basic Info**
- Accelerator Version:  1.3.3
- Install Type: Upgrade from previous versions, initial version 1.2.2
- Upgrade from version: 1.3.2

**Describe the bug**
We had a situation when a workload was able to delete internal (in workload account) ALB. Since installation of internal ALB is managed from accelerator config file, it should not be possible and prevented on SCP level. It has been probably fixed in 1.5.0 version, but @Brian969 asked to open a bug.

**Comment by Brian969** [comment]
- ALB protection added to SCPs in PR#885
