### ISSUE TITLE
[BUG][Functional] NEW-ACCOUNTS does not always create VPCs

### ISSUE THREAD

**Issue by khaws** [aws-samples/aws-secure-environment-accelerator#924]
Bug reports which fail to provide the required information will be closed without action.

**Required Basic Info**
- Accelerator Version:  1.5.0
- Install Type: Clean
- Upgrade from version: N/A

**Describe the bug**
New accounts are vended through ASEA by running the state machine with a scope of `NEW-ACCOUNTS` which first creates a new account and then the associated networking (e.g. VPCs). If, however, the State Machine fails after creating the account (e.g. due to incorrect networking parameters) then re-running the State Machine with `NEW-ACCOUNTS` does not create any networking constructs in the new account. This is because on the second run of the State Machine, the account is no longer "new" and thus, ASEA skips over that account.

**Failure Info**
- What error messages have you identified, if any: None - Step Functions successfully complete execution but without creating any VPCs
- What symptoms have you identified, if any: There are no VPCs in the new account

**Required files**
N/A - Works with the sample config files in the repo as well.

**Steps To Reproduce**
1. Update `config.json` but create wrong networking parameters (e.g. use dynamic allocation but omit the `"cidr-src": "dynamic"` from the `vpc` section
2. Run Step Functions with scope `NEW-ACCOUNTS`
3. Step Functions will fail
3. Fix the `config.json` by adding in `"cidr-src": "dynamic"` in the `vpc` section
4. Re-run Step Functions with scope `NEW-ACCOUNTS`
5. Step Functions will successfully complete
6. There will be no VPCs in the new account

**Expected behavior**
Until the whole account has been setup fully, `NEW-ACCOUNTS` scope should not skip setting up the newly created account.

**Screenshots**
None

**Additional context**
Given how ASEA works, an easier fix would be to update the documents to state that if the initial `NEW-ACCOUNTS` Step Functions fails, all subsequent runs should be with `FULL` scope.

**Comment by archikierstead** [comment]
Did not implement
