### ISSUE TITLE
[BUG] [SM] Syntax Error in config.yaml in asea 1.5.1 (works in 1.5.0)

### ISSUE THREAD

**Issue by joshvmaws** [aws-samples/aws-secure-environment-accelerator#945]
**Required Basic Info**
- Accelerator Version:  1.5.1
- Install Type: Clean
- Which State did the Main State Machine Fail in: Get or Create Configuration from S3

**Describe the bug**
The very first lambda that reads in the config.yaml complains about some invalid characters (at the end of line 1 pointing to the colon). But I don’t have any weird chars in my yaml file. The same config works in asea version 1.5.0

2022-03-17T16:08:28.529Z	9bd47a17-5d58-4660-b83e-f07c689be645	INFO	{
    "acceleratorVersion": "1.5.1",
    "Status": "FAILED",
    "FailedState": "Get or Create Configuration from S3",
    "errorType": "Error",
    "errorMessage": "SyntaxError: Unexpected token (1:13)\n> 1 | replacements:\n    |             ^\n  2 |   addl_regions:\n  3 |     a:\n  4 |       - ca-central-1",
    "trace": [
        "Error: SyntaxError: Unexpected token (1:13)",
        "> 1 | replacements:",
        "    |             ^",
        "  2 |   addl_regions:",
        "  3 |     a:",
        "  4 |       - ca-central-1",
        "    at Runtime.dT0 [as handler] (/var/task/index.js:1392:20111)",
        "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
    ]
}

**Required files**
- Config.yaml file
[config.yaml.zip](https://github.com/aws-samples/aws-secure-environment-accelerator/files/8316517/config.yaml.zip)

**Steps To Reproduce**
1. Copy the config to S3 and follow ASEA deployment guide

**Expected behavior**
The config file must deploy without any errors like it does with the previous version

**Screenshots**
![image](https://user-images.githubusercontent.com/96628998/159288520-c8b03267-dee2-47d4-88ad-2401c5040cc0.png)

**Comment by Brian969** [comment]
Hi - We are aware - it appears v1.5.1 breaks with customers using YAML config files.  Working on a fix.  Sorry.
