### ISSUE TITLE
[BUG] [SM] State machine fails if we want to remove the NFW

### ISSUE THREAD

**Issue by rverma-nsl** [aws-samples/aws-secure-environment-accelerator#967]
Bug reports which fail to provide the required information will be closed without action.

**Required Basic Info**
- Accelerator Version:  1.5.1-a
- Install Type: Upgrade
- Upgrade from version: 1.5.0
- Which State did the Main State Machine Fail in: Phase 1

**Describe the bug**
We have initially created ASEA with NFW but for some reason we don't want to continue with NFW.  After removing NFW section from config.json & manually deleting the firewall, we tried again but got the error as 

```
Unable to retrieve EndpointIds attribute for AWS::NetworkFirewall::Firewall, with error message No object with the provided
 name or resource identifier was found (Service: NetworkFirewall, Status Code: 400, 
 Request ID: 515a244c-8b8e-496a-92d9-4c70d6df5a40, Extended Request ID: null)
```
--

**Comment by Brian969** [comment]
Hi, You needed to let ASEA remove the NFW and not remove it manually - same fix as I provided for SNS applies here.  If it was created using IaC - needs to be managed using IaC, or it will cause you problems :-(.

**Comment by rverma-nsl** [comment]
I even tried that, I added back the firewall, but removed the firewall section from the config. Phase 1 succeeded but firewall is still there.
