### ISSUE TITLE
[BUG] [SM] Get or Create Config from S3 fails with This execition requires Accelerator execution with scope: \"FULL\"

### ISSUE THREAD

**Issue by kbroughton** [aws-samples/aws-secure-environment-accelerator#983]
**Required Basic Info**
* Accelerator Version: v1.5.1-a
* clean run
* Get or Create Config from S3
* config.json based on reference-artifacts/SAMPLE_CONFIGS/config.lite-NFW-example.json

**Describe the bug**

**Failure Info**
```
  "cause": {
    "errorType": "Error",
    "errorMessage": "This execition requires Accelerator execution with scope: \"FULL\"",
    "trace": [
      "Error: This execition requires Accelerator execution with scope: \"FULL\"",
      "    at I2e (/var/task/index.js:1392:22966)",
      "    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
      "    at async Runtime.dT0 [as handler] (/var/task/index.js:1392:17569)"
    ]
  }
```

**Required files**
- I don't see an upload file button anymore for the config.json upload

**Steps To Reproduce**
* Create a brand new account. Make it an Org. Follow all the steps in https://catalog.us-east-1.prod.workshops.aws/workshops/f3ed5d0f-d2f1-47e8-a305-168da9179aaa/en-US/sea-administrators
to setup the org and root account.
* Upload the attached file to an S3 bucket
* Launch the AWSA CF template using latest release

**Expected behavior**
State machine does not fail

**Screenshots**

**Additional context**
I had to retry the pipeline several times, and the state-machine twice to make it to this error.

The error message maps to a few lines in get-or-create-config.ts #L396
https://github.com/aws-samples/aws-secure-environment-accelerator/blob/1df3f9a8a124476aa73cd2212393a588212fe238/src/core/runtime/src/get-or-create-config.ts#L396

I haven't been able to figure out what scope is supposed to map to in the config.json

**Comment by Brian969** [comment]
Hi,
When you run the State Machine, provide the following input: 
{ "scope": "FULL", "mode": "APPLY", "verbose": "0" }

documented [here](https://aws-samples.github.io/aws-secure-environment-accelerator/installation/sm_inputs/#125-state-machine-scoping-inputs) and it will proceed without issue.

i.e.
![image](https://user-images.githubusercontent.com/56414362/170800428-88fc21e4-a54a-4030-9193-7f1536c19f56.png)


(on your previous ticket - I'll try to add something on the topic the next time I update the docs.)

**Comment by kbroughton** [comment]
that fixed it, thanks
