### ISSUE TITLE
[DOCS] [ENHANCEMENT] root account name default ASEA-Main causes "does not match the name in the Accelerator configuration ASEA-Main" error

### ISSUE THREAD

**Issue by kbroughton** [aws-samples/aws-secure-environment-accelerator#984]
**Required Basic Info**
* Accelerator Version: v1.5.1-a
* troubleshooting initial run
* Load Organization Configuration
* config.json based on reference-artifacts/SAMPLE_CONFIGS/config.lite-NFW-example.json

**Describe the bug**

**Failure Info**
```
{
  "errorType": "Error",
  "errorMessage": "There were errors while loading the configuration:\nexample-technologies does not match the name in the Accelerator configuration ASEA-Main",
  "trace": [
    "Error: There were errors while loading the configuration:",
    "example-technologies does not match the name in the Accelerator configuration ASEA-Main",
    "    at Runtime.X40 [as handler] (/var/task/index.js:1381:341)",
    "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
  ]
}
```
scrubbed name: example-technologies
It seems a general issue I'm facing is that the errors don't reference the config or parameters source which then get translated to other run-time variable names.  

example-technologies is the alias of the root account and is listed as the "Management account name" under "Organizations" | "Settings", but I don't see it in the Cloudformation parameters or the config.json file.  I'm not sure how I can change this value or what other value it's conflicting with.
 

**Required files**
- I don't see an upload file button anymore for the config.json upload

**Steps To Reproduce**
* Create a brand new account. Make it an Org. Follow all the steps in https://catalog.us-east-1.prod.workshops.aws/workshops/f3ed5d0f-d2f1-47e8-a305-168da9179aaa/en-US/sea-administrators
to setup the org and root account.
* Upload the attached file to an S3 bucket
* Launch the AWSA CF template using latest release

**Expected behavior**
State machine does not fail

**Screenshots**

**Additional context**

Tracing the error message to the code, it becomes more clear what the problem is. "ASEA-Main is not the name of the Accelerator configuration variable, but rather the default "account-name".
```
      if (accountInOu?.Name !== accountConfig['account-name']) {
        errors.push(
          `${accountInOu?.Name} does not match the name in the Accelerator configuration
${accountConfig['account-name']}`,
        );
      }
```

The default configuration should be changed to a "Changeme" value as it could be construed that this doesn't need to be changed and is a reasonable default. The Documentation should include a step stating this must match the root account-alias.
```
    "management": {
      "account-name": "ASEA-Main",
```

The error message would be more clear if it read
"X does not match the name in the value from the Accelerator config.json file:  "ASEA-Main"

**Comment by Brian969** [comment]
Good suggestion, we can better clarify.  Thanks!
