### ISSUE TITLE
[BUG][SM] Support managing nested OUs in CT setup

### ISSUE THREAD

**Issue by danieloldberg** [aws-samples/aws-secure-environment-accelerator#986]
**Required Basic Info**
To properly assess the enhancement request, we require information on the version of the Accelerator you based this request upon:
- Accelerator Version: v1.5.1-a

**Is your feature request related to a problem? Please describe.**
I can't find any documentation or examples of this, please let me know if there already is a solution for this.
It would be really nice to be able to manage nested OUs in a Control Tower setup. Some situations might benefit from a hierarchical OU structure. My understanding is that the current version support creating accounts within nested OUs using ou-path and applying SCPs and other settings for that specific account. My use case is more managing the actual child OUs.

**Describe the solution you'd like**
Maybe an optional ou-path / parentOU parameter within the configuration file, or just write ParentOU/NameOfChildOU in the OU object name. Then just configure the OU just like any other.

**Describe alternatives you've considered**
Deploying a more flat OU structure where individual settings need to be configured in many places.

**Additional context**

**Comment by archikierstead** [comment]
Did not implement
