### ISSUE TITLE
[BUG][DOCS] No instructions for where to put certs or that they are required

### ISSUE THREAD

**Issue by kbroughton** [aws-samples/aws-secure-environment-accelerator#987]
Since there was no mention of the certificates in the documentation [workshop](https://catalog.us-east-1.prod.workshops.aws/workshops/f3ed5d0f-d2f1-47e8-a305-168da9179aaa/en-US/sea-administrators) I assumed that AWS would use its certificate manager to create some default certs for me.

However, I get an error. 

**Required Basic Info**
Accelerator Version: v1.5.1-a
troubleshooting initial run
Load Accounts
config.json based on reference-artifacts/SAMPLE_CONFIGS/config.lite-NFW-example.json

**Describe the bug**
There is no indication of where we are supposed to upload the certificate key material to, or formats, or requirements.

```
"There were errors while loading the configuration:\nFileCheck: File not found at
 \"s3://asea-management-phase0-configuswest2-xxxxxxxxxxxx/certs/example1-cert.crt\"\nFileCheck: 
File not found at \"s3://asea-management-phase0-configuswest2-xxxxxxxxxxxx/certs/example1-cert.key\"
```

The blocks in the https://github.com/aws-samples/aws-secure-environment-accelerator/blob/main/reference-artifacts/SAMPLE_CONFIGS/config.lite-NFW-example.json file we are using look like this:
```
      "certificates": [
        {
          "name": "PerimSelf-SignedCert",
          "type": "import",
          "priv-key": "certs/example1-cert.key",
          "cert": "certs/example1-cert.crt"
        }

      "certificates": [
        {
          "name": "DevSelf-SignedCert",
          "type": "import",
          "priv-key": "certs/example1-cert.key",
          "cert": "certs/example1-cert.crt"
        }
```

But it's not clear where to upload these crts to. These should probably be uploaded to ACM but it is not clear from the instructions.
All required modifications should be part of the workshop documentation.

**Expected update**
I would expect a section on creating appropriate keys/certs, and where to upload.
Or ideally, if the certs haven't been uploaded, that AWS Cert Manager would create any required certs.

Creation of the certs is described here, but it is not referenced by the main documentation.
https://github.com/aws-samples/aws-secure-environment-accelerator/blob/main/reference-artifacts/Certs-Sample/To_Create_Self_Signed-Cert.txt

There are no instructions on how to present these to the State Machine.

**Additional context**

**Comment by kbroughton** [comment]
The error explains where the certs should be
`s3://asea-management-phase0-configuswest2-xxxxxxxxxxxx/certs/example1-cert.key`
Creating the keys according to the text file and uploading to a certs folder in that bucket fixed the issue.

**Comment by Brian969** [comment]
- This is defined in step 8 in section [1.5](https://aws-samples.github.io/aws-secure-environment-accelerator/installation/install/#15-basic-accelerator-configuration) of the ASEA install guide.
- We can't auto-generate certs, as part of the process is domain verification, which requires manual work on your behalf.
- Also don't want to 'encourage' the use of self-signed certs as they are BAD
- Suggest reviewing [FAQ#1.6.3](https://aws-samples.github.io/aws-secure-environment-accelerator/faq/#what-is-the-recommended-approach-to-manage-the-alb-certificates-deployed-by-the-accelerator) - it covers the 3 mechanisms for supplying, or auto-generating certs.
- I can suggest to those maintaining the workshop to add a reference on this topic.
- I do strongly encourage you to read the [Install Guide](https://aws-samples.github.io/aws-secure-environment-accelerator/installation/install/) top to bottom, as well as all the [FAQ](https://github.com/aws-samples/aws-secure-environment-accelerator/edit/master/docs/faq/index.md)'s.

**Comment by Brian969** [comment]
Yes, always the single source customer bucket.  NEVER touch anything in the "asea-config" bucket.  That bucket is the resultant set of files used for a deployment (we copy repo files and overwrite with customer bucket files as appropriate).  We never overwrite anything in the customer bucket.
