### ISSUE TITLE
[BUG] [SM] Error while executing command: sh docker-entrypoint.sh in Deploy Phase 3

### ISSUE THREAD

**Issue by kbroughton** [aws-samples/aws-secure-environment-accelerator#988]
**Required Basic Info**
Accelerator Version: v1.5.1-a
troubleshooting initial run
Deploy Phase 3
config.json based on reference-artifacts/SAMPLE_CONFIGS/config.lite-NFW-example.json

**Describe the bug**
Deploy Phase 3 fails running docker-entrypoint.sh

**Failure Info**

```
       },
        {
          "Contexts": [
            {
              "Message": "Error while executing command: sh docker-entrypoint.sh. Reason: exit status 1",
              "StatusCode": "COMMAND_EXECUTION_ERROR"
            }
          ],
          "DurationInSeconds": 5025,
          "EndTime": 1654134324790,
          "PhaseStatus": "FAILED",
          "PhaseType": "BUILD",
          "StartTime": 1654129299538
        },
        {
          "Contexts": [
            {
              "Message": "Error while executing command: if [ $buildComplete = \"complete\" ]; then echo \"Build Finished\"; else echo \"Build did not finish. please review logs for errors!\" && exit 1; fi. Reason: exit status 1",
              "StatusCode": "COMMAND_EXECUTION_ERROR"
            }
          ],
```

In the cloudwatch logs, there are three Log Groups for Deploy Phase 3, but none have any errors that I could see.

ConfigRuleEc2Instance
CustomSecurityHubAcceptInvite
CustomSecurityHubEnabled

**Expected behavior**
Deploy Phase 3 runs without error
Errors are more detailed

**Screenshots**

**Additional context**

Duration 5025s suggests it ran for a long time before failing

**Comment by Brian969** [comment]
- believe you looked in the wrong log files - you need to review the CodeBuild logfile itself.
- the error at the bottom is quasi-meaningless as it just indicates an error occured
- Decent instructions on troubleshooting can be found in the operations guide, troubleshooting [section](https://github.com/aws-samples/aws-secure-environment-accelerator/edit/master/docs/operations/troubleshooting.md).  The Step Functions GUI has changed, so the instructions won't be exact, but they should be pretty close.  Specifically in the State machine log, you need to find the FIRST occurrence of UPPERCASE FAIL (not the second or last).

**Comment by kbroughton** [comment]
I can see my AutoScaling quotas are still mostly "Not available". This is now over 6 days since account creation and 3 Service Help requests.

![Screen Shot 2022-06-02 at 9 44 09 AM](https://user-images.githubusercontent.com/10562482/171656041-b65a041f-7030-47fe-8194-562ad4eaf3f1.png)
