### ISSUE TITLE
[BUG] [SM] Difficult to request increase in limits for created sub-accounts

### ISSUE THREAD

**Issue by kbroughton** [aws-samples/aws-secure-environment-accelerator#989]
**Required Basic Info**
Accelerator Version: v1.5.1-a
troubleshooting initial run
Deploy Phase 3
config.json based on reference-artifacts/SAMPLE_CONFIGS/config.lite-NFW-example.json

**Describe the bug**
The logs show an error for VCPU limits associated with the Logging account.
The sub-accounts are auto-generated, and it's not obvious how to log into them. Switch account doesn't work for root users and you are not allowed to login with a user account due to the SCP Quarantine policy which cannot be removed.
It would be nice if the Troubleshooting documentation mentioned logging in with the wsaws+aseaT-log or similar account and use the "Forgot Password" flow to obtain the first password for auto-generated accounts.

Finally, once logged into the sub-account "Logging", there are SCPs which block me from creating a support case or requesting an increase in limits. I requested an increase in limits from the root account with at "Developer" plan, but it has been over 48 hours with no response (SLO is 12 hrs) so I hoped to try the self-service Limits Increase Request. But this is not possible.
Given that Limits has caused a delay of over a week for this project, it would be nice if the SCP didn't block it. Even better, maybe ASEA could detect these Limit errors and automatically submit the correct request for me.

**Failure Info**
I increased the limits for the root account and checked that I can deploy 2x t3.large's to my root management account, however,
it appears that the limits are in the logging account: arn:aws:organizations::5*******:account/o-iipxxxxxxxx/6*********

Because ASEA deploys a quarantine SCP, I cannot make the EC2 vcpu limit request from the logging account: 6************

```
Stack ASEA-Operations-Phase3 has an ongoing operation in progress and is not stable (ROLLBACK_IN_PROGRESS 
(The following resource(s) failed to create: [RsyslogAsgoperationsRsyslogAutoScalingGroup99D0DB42]. Rollback requested by user.))
ASEA-Operations-Phase3 | 70/72 | 6:48:49 PM | CREATE_FAILED        | AWS::AutoScaling::AutoScalingGroup  |
 OperationsPhase3/RsyslogAsgoperations/RsyslogAutoScalingGroup (RsyslogAsgoperationsRsyslogAutoScalingGroup99D0DB42) Group did not stabilize. {current/minSize/maxSize} 
group size = {0/1/2}. Failed Scaling Activity: You have requested more vCPU capacity than your current vCPU limit of 1 allows
 for the instance bucket that the specified instance type belongs to. Please visit 
http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit. Launching EC2 instance failed.
    new RsysLogAutoScalingGroup (/app/src/lib/cdk-constructs/src/vpc/asg.ts:65:5)
    \_ createAsg (/app/src/deployments/cdk/src/deployments/rsyslog/step-2.ts:212:3)
    \_ Object.step2 (/app/src/deployments/cdk/src/deployments/rsyslog/step-2.ts:73:5)
    \_ deploy (/app/src/deployments/cdk/src/apps/phase-3.ts:121:27)
    \_ processTicksAndRejections (internal/process/task_queues.js:95:5)
    \_ Object.deploy (/app/src/deployments/cdk/src/app.ts:87:3)
    \_ main (/app/src/deployments/cdk/cdk.ts:92:16)
ASEA-Operations-Phase3 | 70/72 | 6:48:51 PM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack                | ASEA-Operations-Phase3 The following resource(s) failed to create: [RsyslogAsgoperationsRsyslogAutoScalingGroup99D0DB42]. Rollback requested by user.

```

**Required files**

**Steps To Reproduce**
Deploy stack. State machine fails.

**Expected behavior**
I expect that ASEA would provide guidance as to how to troubleshoot switching to non-management accounts.
I expect that ASEA would not prevent me from making Limit Increase requests directly from sub-accounts.

**Screenshots**
![support_request_unavailable](https://user-images.githubusercontent.com/10562482/172006976-7c4aff7d-34ac-49a1-9efd-84d6ad9ef8ab.png)

**Additional context**
By the way, is there any way to "startAt": "Deploy Phase 3" or something similar in the execution input? It's starting to get quite long in the test/patch cycle.

**Comment by kbroughton** [comment]
Further trying to resolve this, it seems that any problem with the StateMachine that requires troubleshooting in the non-management account will be impossible due to the `ASEA-Quarantine-New-Object` SCP shown below:
```
      "Effect": "Deny",
      "Action": "*",
      "Resource": "*",
      "Condition": {
        "ArnNotLike": {
          "aws:PrincipalARN": [
            "arn:aws:iam::*:role/OrganizationAccountAccessRole",
            "arn:aws:iam::*:role/aws*",
            "arn:aws:iam::*:role/ASEA-*"
          ]
```

The root/management account and all subaccounts are prefixed wsaws+<something>@example.com.
I Think it would be helpful to include `arn:aws:iam::*:root` in the list of "BreakGlassPrinciples" so that one could login to the sub-account and troubleshoot with acceptable privileges.

Note that the policy doesn't seem to apply to the management/org root account, only the generated accounts.
It is not possible to switch role from the root to the sub because you cannot create the bindings in the subaccount, nor login to a newly created user account in the management account due to the SCP.

**Comment by Brian969** [comment]
- You can access any of the subaccounts by assuming the role ASEA-PipelineRole or OrganizationAccountAccessRole from the Organization Management account (the first having the most access, once it has been created).

**Comment by kbroughton** [comment]
Hi @Brian969 , the problem is that currently I only have the root account for the mgmt and all sub accounts.
The root account cannot switch to another account.
I created a user in the mgmt account, but due to the SCP I cannot login with a user account.
See screenshots below.
![root_switch](https://user-images.githubusercontent.com/10562482/172267588-99445a56-5861-4ced-89ca-555c95e68d2f.png)
![user_switch](https://user-images.githubusercontent.com/10562482/172267589-812310fe-d06c-4ceb-ac4c-40622520162f.png)

**Comment by Brian969** [comment]
Hey,
- correct the root user cannot assume roles, you need an IAM user in the Mgmt account with Administrative priv's
- SCP's do not apply to the Management account (ever), so you should be able to login as this new user in the Mgmt account
- Once logged in to the IAM user, you can assume roles in the sub-accounts (`Switch role` on the above screen), either: `ASEA-PipelineRole` or `OrganizationAccountAccessRole`

**Comment by kbroughton** [comment]
Thankyou, I believe I was missing the Admin role attached to the user when I tried this before. Switch role worked as you described.
