### ISSUE TITLE
[ENHANCEMENT] Upgrade to CDKv2

### ISSUE THREAD

**Issue by drewdresser** [aws-samples/aws-secure-environment-accelerator#994]
CDK v1 recently entered [maintenance mode](https://docs.aws.amazon.com/cdk/v1/guide/home.html). 

During the maintenance phase, CDK v1 will receive critical bug fixes and security patches only. New features will be developed exclusively for CDK v2 during the v1 maintenance phase.

On June 1, 2023, support will end for AWS CDK v1.

It would be nice to upgrade SEA to CDK v2 before that support end date (~1 yr from now)

**Comment by Brian969** [comment]
Thanks and yes, we are aware.  We already added this to the backlog and had yet to post here.  A potential for the 1.5.3 release as we will be pushing v1.5.2 soon.

**Comment by rverma-nsl** [comment]
Would love to see if the stack can be simplified too like https://github.com/awslabs/landing-zone-accelerator-on-aws/tree/main/source/packages/%40aws-accelerator

SEA is more functional and rich but at the same time more complex. The last few releases specially 1.5+ were very nice. I would love to contribute to the project, especially for cdk upgrade-related tasks. 
@Brian969  Can you add some more fine-grained tasks which I can pick independently?

Thanks
