### ISSUE TITLE
[BUG][SM] Workload account VPC variable using first VPC name when adding second VPC

### ISSUE THREAD

**Issue by ColinL2021** [aws-samples/aws-secure-environment-accelerator#996]
Bug reports which fail to provide the required information will be closed without action.

**Required Basic Info**
- Accelerator Version:  v1.5.1-a
- Install Type: N/A
- Upgrade from version: N/A
- Which State did the Main State Machine Fail in: (e.g. N/A, Phase 0) Does not fail.

**Describe the bug**
(A clear and concise description of what the bug is.)
When creating a second VPC in a Workload OU the variable ${CONFIG::VPC_NAME} used to create the Route Table and add the CIDR's to the NACL uses the first VPC name. The State Machine completes successfully without error. 
Deploying in same or different region has same result. 

**Failure Info**
- What error messages have you identified, if any: No errors reported
- What symptoms have you identified, if any: Route table uses name of first VPC and NACL deny list has CIDR's of first VPC.

**Required files**
- Please provide a copy of your config.json file (sanitize if required) - Added
- If a CodeBuild step failed- please provide the full CodeBuild Log - N/A
- If a Lambda step failed - please provide the full Lambda CloudWatch Log - N/A
- In many cases it would be helpful if you went into the failed sub-account and region, CloudFormation, and provided a screenshot of the Events section of the failed, deleted, or rolled back stack including the last successful item, including the first couple of error messages (bottom up)

**Steps To Reproduce**
1. Go to a Workload OU (i.e. Dev)
2. Copy the VPC section and paste in a second VPC section. 
3. Change the name of the VPC to a manual entry of your choosing (i.e. Dev2)
4. Optionally update the CIDR ranges to a provided range or use dynamic if space available in CIDR pool
5. Save and commit to CodeCommit
6. Run the Main State Machine
7. Observe the Route table name/values. Name should be of the first VPC. Two Route tables of same name if deployed in same region. 
8. Observe the NACL CIDR values for subnets in the new VPC of the first VPC

**Expected behavior**
Expected the Route Table to have the name of the new VPC in the name. Also, expected the CIDR range added to the NACLs of the new subnets to have the correct values instead of the first VPC.

**Screenshots**

**Additional context**
Sample has example in the Preprod OU.
[config-sanitized.json.zip](https://github.com/aws-samples/aws-secure-environment-accelerator/files/8893587/config-sanitized.json.zip)

**Comment by Brian969** [comment]
Agreed, the variable should point to the VPC object it is inside, not the first VPC object within the parent object.

**Comment by archikierstead** [comment]
Did not implement
